### ISSUE TITLE
Modifying php.snippets given by vim-snippets

### ISSUE THREAD

**Issue by andrewhylee** [honza/vim-snippets#1007]
is the Title possible?

I wanted to use html.snippets given by vim-snippets on my php files.
So I thought it would work by extending the php.snippets file (given by vim-snippets) to include html but I realized that I cannot edit the php.snippets file (given by vim-snippets).

Thank you

**Comment by lpil** [comment]
You could perhaps configure ultisnips to load additional languages using `:UltiSnipsAddFiletypes` :)
