### ISSUE TITLE
Snippet for generating random UUID

### ISSUE THREAD

**Issue by fenuks** [honza/vim-snippets#1028]
Hello, thank you for maintaining this useful list. I wonder if there is a place (in `all.snippets` I suppose) for snippet generating random UUID? 

Simple snippet I wrote for that purpose is as follows.

```
snippet uuid "Random UUID" w
`!p if not snip.c: import uuid; snip.rv = uuid.uuid4()`
endsnippet
```

**Comment by lpil** [comment]
Sounds good to me :)

**Comment by fenuks** [comment]
I'm glad to hear that. :-) Would you like me to create merge request, or you will add it yourself?

**Comment by lpil** [comment]
Please make a pull request :)
