### ISSUE TITLE
Proposed extended snippet for Tex

### ISSUE THREAD

**Issue by pascalwhoop** [honza/vim-snippets#1045]
Hi,
I extended a snippet for my personal use and thought I'd share it

https://gist.github.com/pascalwhoop/8024ba96b1c309077a5d3b069ae8fa58

maybe that is a bit better than the barebones version. They could also live side by side with a different tag to expand on

**Comment by lpil** [comment]
Looks good. Want to make a pull request @pascalwhoop ?

**Comment by felixwege** [comment]
I believe this issue can be closed since #1046 was merged.

**Comment by lpil** [comment]
Thank you
