### ISSUE TITLE
Ho do I include own snippets?

### ISSUE THREAD

**Issue by crapp** [honza/vim-snippets#1059]
Hi,

I want to add my own c++ snippets which I use frequently at my workplace. The snippets are pretty project specific so I can't add to your vim-snippets plugin. But where can I add them? 

My options as I see them. 

1. Fork your project --> Lots of work for 3 or 4 Snippets
2. Create my own snippets plugin --> Even more work for such a task
3. Change the plugin files locally and stash them whenever I try to update vim-snippets --> Complicated and how do I synchcronize my changes?

Any suggestions?

Thank you very much

**Comment by lpil** [comment]
It's straightforward to create your own snippets plugin. Here's a very simple example: https://github.com/lpil/my-vim-snippets

**Comment by crapp** [comment]
Thanks! I just realized UltiSnips has a built in function to edit / add snippets

https://www.youtube.com/watch?v=f_WQxYgK0Pk
