### ISSUE TITLE
Freemarker snippets available on my repo

### ISSUE THREAD

**Issue by caneta** [honza/vim-snippets#1065]
Hi everyone.

I've written some UltiSnip snippet for the [freemarker](https://freemarker.apache.org/) template language: [here is my repo](https://github.com/caneta/neovim_notes/tree/master/UltiSnips).

Freemarker is a web template engine used by the Java based [Liferay](https://www.liferay.com/) portal.

I use these snipptes on a daily basis and maybe someone else can find them useful too.

Waiting for feedback and suggestions!

**Comment by honza** [comment]
We'd be happy to include these in the repo, if you want.

**Comment by caneta** [comment]
It would be great @honza , thanks!

**Comment by lpil** [comment]
Please make a PR @caneta :)

**Comment by caneta** [comment]
[Done](https://github.com/honza/vim-snippets/pull/1075).

**Comment by lpil** [comment]
👍
