### ISSUE TITLE
Import css in React

### ISSUE THREAD

**Issue by xavierartot** [honza/vim-snippets#1071]
How can I import CSS in React?
We're using Component Styled, the trend is to use pure CSS in a template ES6.

```
const Title = styled.h1`
  font-size: 1.5em;
  text-align: center;
  color: palevioletred;
`;
```

**Comment by lpil** [comment]
Additional snippets can be imported using your snippet plugin. Ultisnips offers `:UltiSnipsAddFiletypes`

https://github.com/honza/vim-snippets#vendor-snippets
