### ISSUE TITLE
Indiscriminate mixing of tabs and spaces in Scheme snippets

### ISSUE THREAD

**Issue by cwfoo** [honza/vim-snippets#1073]
For example:

https://github.com/honza/vim-snippets/blob/2af1ffe88d3de3fbe40a6e74fb626b18a6548cbd/snippets/scheme.snippets#L1-L3

Notice the tab after the `+`.

https://github.com/honza/vim-snippets/blob/2af1ffe88d3de3fbe40a6e74fb626b18a6548cbd/snippets/scheme.snippets#L28-L30

Similarly, notice the tab after `cond`.

@dhilipsiva

**Comment by lpil** [comment]
Is this what you would expect @cwfoo ? https://github.com/honza/vim-snippets/pull/1074

**Comment by cwfoo** [comment]
@lpil Almost. I forgot give examples of other unwanted tabs. Example:

https://github.com/honza/vim-snippets/blob/2af1ffe88d3de3fbe40a6e74fb626b18a6548cbd/snippets/scheme.snippets#L35-L36

There shouldn't be a tab before `true-action`. Same goes for `false-action`. Instead of a tab, it should be two spaces.

Another example:

https://github.com/honza/vim-snippets/blob/2af1ffe88d3de3fbe40a6e74fb626b18a6548cbd/snippets/scheme.snippets#L20

**Comment by lpil** [comment]
So like this?

```scheme
(if some-value
(true-func)
(false-func))
```

I would have expected this:

```scheme
(if some-value
  (true-func)
  (false-func))
```

**Comment by cwfoo** [comment]
> Snippet files should never uses spaces, the plugin expands tabs to your editor's indentation settings, be it tabs or any number of spaces.

Oh I see. #1074 is all good then.

**Comment by lpil** [comment]
Thank you :)

**Comment by dhilipsiva** [comment]
Apologies @cwfoo I was on a long vacation. Glad that this is fixed now. :)
