### ISSUE TITLE
Duplicates in `texmath.snippets`

### ISSUE THREAD

**Issue by fsonner** [honza/vim-snippets#1083]
`UltiSnips/texmath.snippets` contains some snippets duplicating behaviors already in `snippets/tex.snippets`, some of which have less features than the ones in `snippets/tex.snippets`.

**Comment by Zeta611** [comment]
I've been actively using snippets `eqnn` and `alnn`, which don't exists in `tex.snippets`.
I was a bit confused when I couldn't use some snippets—and commit 4ff8115 broke my vim-TeX environment.
Perhaps leaving the ones with different snippet shortcuts might be a good idea?

**Comment by lpil** [comment]
Ah, yes, that would have been preferable. I didn't realise that the patch removed some functionality in addition to some duplication, I wouldn't have merged if I had realised that. My bad.

Would you like to make a PR fixing this? Or shall I revert the patch?

**Comment by Zeta611** [comment]
This would fix the issue & added tabstops @fsonner mentioned as "less features"!
