### ISSUE TITLE
Type Hinting In Python def Snippet

### ISSUE THREAD

**Issue by ZaydH** [honza/vim-snippets#1095]
Python 3 allows type declarations in the function definition.  See here in [PEP 484](https://www.python.org/dev/peps/pep-0484/#abstract).  If I define a function with a type as shown below:

`def my_func(x: TypeOfX):`

The generated snippet looks like (in Sphinx format):
```
"""TODO: Docstring for my_func.

:param x: TypeOfX: TODO
:returns: TODO

"""
```
Observe that "`TypeOfX`" is included in the `param` line of `x`.

In other IDEs (PyCharm), it does not add the type to the docstring.  I looked and could not find anywhere where this was specified as the standard (I admittedly could have missed it).  Is this expected?

**Comment by rmrao** [comment]
So beyond just inserting type hints into the docstring, this seems to also be a bug when declaring classes. When I add a type hint to the `__init__` in the `class` snippet, it ends up expanding like this

```python
class MyClass(object):

    def __init__(self, arg1: float, arg2: int):
        super(MyClass, self).__init__()
        self._arg1: float = arg1: float
        self._arg2: int = arg2: int
```

which is actually incorrect behavior. It seems like the best way of handling this is to change the `Arg` class around [here](https://github.com/honza/vim-snippets/blob/cbbf1559166f9c308ae0f4634c11bdf282ddafba/UltiSnips/python.snippets#L54) from

```python
class Arg(object):
    def __init__(self, arg):
        self.arg = arg
        self.name = arg.split('=')[0].strip()
```

to something more like this

```python
class Arg(object):
    def __init__(self, arg):
        self.arg = arg
        name_and_type = arg.split('=')[0].split(':')
        self.name = name_and_type[0].strip()
        self.type = name_and_type[1].strip() if len(name_and_type) == 2 else None
```

This would fix the class init bug and also provide and easy way to update the docstring. If this seems reasonable I can submit a pull request.

**Comment by lpil** [comment]
Sounds good to me :)

**Comment by rmrao** [comment]
Submitted a pull request for this, and also to fix an issue with varargs where they would be added like this:

```python
def __init__(self, *args, **kwargs):
    self._*args = *args
    self._**kwargs = **kwargs
```

I just filtered them out of the snippet.

The pull request will also change docstrings so that type doesn't get added automatically. I believe for some docstring formats type should be added. E.g. I think Google's is something like

```
Args:
    arg1 (type): description
Returns:
    (type): description
```

but I'm not totally sure.

**Comment by lpil** [comment]
Thanks! Can this be closed now?

**Comment by rmrao** [comment]
Probably? The initial issue is fixed I think. I have the code to make Google style docstrings automatically include type hinting working, at least according to [this](https://www.datacamp.com/community/tutorials/docstrings-python#fifth-sub).

Numpy and sphinx seem to be trickier, and I don't personally use them so we could either leave it be or I can submit a pull request for the google docstring change alone.

**Comment by lpil** [comment]
OK, thanks. If anyone has further problems please open a new issue
