### ISSUE TITLE
Doesn't work without the ultisnip plugin

### ISSUE THREAD

**Issue by astier** [honza/vim-snippets#1127]
Coc does not suggest snippets  if I install coc-snippets. Coc only suggests snippets if I install the ultisnips plugin (works even if I uninstall coc-snippets). I thought ultisnips isn't required?

**Comment by astier** [comment]
I tested it with tex, sh and vim files.

**Comment by lpil** [comment]
Ultisnips specifically is required but a compatible snippet engine is. https://github.com/honza/vim-snippets#snippet-engines-supporting-vim-snippets
