### ISSUE TITLE
rails.snippets file not loaded

### ISSUE THREAD

**Issue by diegobassan** [honza/vim-snippets#1141]
When using a * .rb file, the _rails.snippets_ snippet is not loaded.
Unlike opening a * .html.erb file for example, which loads both _eruby.snippets_ and _html.snippets_ when executing: _CocList snippets_.

How can I configure _rails.snippets_ to be loaded along with _ruby.snippets_ when editing a * .rb file?

**Comment by diegobassan** [comment]
vim version: NVIM v0.4.0-dev
node version: v8.10.0
coc.nvim version: 0.0.73
term: screen-256color
platform: linux

**Comment by lpil** [comment]
There's some information here on loading vendor snippets -> https://github.com/honza/vim-snippets#vendor-snippets

For rails specifically the rails.vim will do lots of useful rails things including load these snippets when you're in a rails project https://github.com/tpope/vim-rails
