### ISSUE TITLE
Position cursor at 2nd occurence of item?

### ISSUE THREAD

**Issue by lesurp** [honza/vim-snippets#1151]
Hi,

I'm writing a simple snippet:

```rust
println!("$1: {}", $1);
```

When expanding, the cursor obviously goes to the first `$1` however I would prefer to have it at the second one. This would allow me to use my language completion if the printed expression includes call to method etc.

Is this possible?

**Comment by lpil** [comment]
Like this :)
```rust
println!("$1: {}", ${1});
```
