### ISSUE TITLE
Do we need more snippets for Fortran?

### ISSUE THREAD

**Issue by yhu266** [honza/vim-snippets#1178]
I have a small collection of Fortran snippets [here](https://github.com/yhu266/vim-fortran-snippets). Some of them do include UltiSnips features.

My question is, should I contribute them to this repo? Or just leave it as separated? How can we tell whether a snippet is generally accepted or of personal flavor?

Thanks!

**Comment by lpil** [comment]
New snippets are accepted! We try not to clash with any existing triggers though

**Comment by yhu266** [comment]
> New snippets are accepted! We try not to clash with any existing triggers though

That's great! I'll make sure the new ones are backward compatible!
