### ISSUE TITLE
[Feature] a command for list all snippets

### ISSUE THREAD

**Issue by zodman** [honza/vim-snippets#1202]

**Comment by brainplot** [comment]
I know I'm late but the [fzf.vim plugin](https://github.com/junegunn/fzf.vim) provides this with the `:Snippets` command.

**Comment by lpil** [comment]
Brilliant, thank you @brainplot !

**Comment by zoj613** [comment]
> I know I'm late but the [fzf.vim plugin](https://github.com/junegunn/fzf.vim) provides this with the `:Snippets` command.

thanks for this, had to resort to using this feature via fzf.vim sinc the `g:UltiSnipsListSnippets` option does not work for me.

cc @honza
