### ISSUE TITLE
auto inserting into vim

### ISSUE THREAD

**Issue by douglas86** [honza/vim-snippets#1218]
What is the best way to automatically update vim, say for instance I want to insert useState hook into my program. How will I get vim to auto update the import statement so that it looks something like this: import React, { useState } from "react". it should just insert the brackets and the useState, how would I achieve that task any ideas would be greatly appreciated.

**Comment by lpil** [comment]
I'm sorry but I don't understand your question, could you explain the behaviour in steps please?

**Comment by douglas86** [comment]
for example:
this is a simple react program

import React from "react"

function App() {
 return (
  <div>
    <p>Body</p>
  </div>
 )
}

export default App

as soon as I insert useState it should display useState at the top

#it will automatically insert { useState } as soon as useS snippet is triggered
#without me going to the top of my file and putting it there manually
#I should be using the useS snippet on line 4

1. import React, { useState } from "react" 
2. 
3.   function App() {
4.    const [title, useTitle] = useState("")
5.     return (
6.       <div>
7.         <p>Body</p>
8.       </div>
9.     )
10. }
11. 
12. export default App

I hope that, that make more sense.

**Comment by lpil** [comment]
I see! This is not something a snippet engine can do for you, you would need to look into creating your own vim plugin or a more general React IDE like tool. Good luck!

**Comment by fabriziobertoglio1987** [comment]
@douglas86 I do something similar with java 
I copied this code in my configs https://vim.fandom.com/wiki/Add_Java_import_statements_automatically

but I think you can easily and better do this with coc, nvim and typescript language server with js/typescript
