### ISSUE TITLE
impl snippet for rust

### ISSUE THREAD

**Issue by yigitsever** [honza/vim-snippets#1223]
Current `impl` snippet for rust in only available on snipmate syntax and the nesting is wrong for Ultisnips. Once expanded it looks like;

```
impl Type/Trait for ${3:Type} {

}
```

Two cases for impl syntax, for instance, is either;

`impl Summary { ...`

or 

`impl Summary for NewsArticle { ...`

so `for` should be there for two tokens.

A snippet on UltiSnips syntax like;
```
snippet impl "Struct/Trait implementation"
impl ${1:Type/Trait}${2/..*/ for /}$2 {
    ${0}
}
endsnippet
```
would work but the jump forward trigger from $1 to $2 stands in place.

I can happily send a pr for the snippet above but I was wondering if there is a more elegant solution.

**Comment by yigitsever** [comment]
Turns out this snippet was already there but was removed with df26062a37500390c53f3efa7462384a86695e89

**Comment by lpil** [comment]
Looks like a mistake, for sure. If you would like to fix this please submit a PR, thank you
