### ISSUE TITLE
javascript_react file type

### ISSUE THREAD

**Issue by brandoncc** [honza/vim-snippets#1236]
Thanks for this great repo!

The react snippets don't work for me because neovim calls jsx files javascriptreact, but your file is javascript_react. Is there a solution for this?

**Comment by brandoncc** [comment]
I solved it by adding this to my ultisnips config:

```vim
" honza/vim-snippets uses javascript_react and javascript-react
autocmd BufRead,BufNewFile *.jsx setlocal filetype=javascriptreact.javascript-react.javascript_react
```

**Comment by brandoncc** [comment]
Unfortunately my change broke coc.nvim :-/

**Comment by RaveHunter05** [comment]
@brandoncc where is the ultisnips config file? i can't use html stuff inside .jsx files, can you help me please?

**Comment by RaveHunter05** [comment]
already solved the problem, in my case i had to add all the code in my .vimrc, i use vim, not neovim

**Comment by brandoncc** [comment]
Hi @RaveHunter05,

I recently found `UltiSnipsAddFiletypes`. Check out `:help UltiSnipsAddFiletypes` for more information.

I think this is what you need to add to your vim config:

```vim
:UltiSnipsAddFiletypes javascriptreact.html
:UltiSnipsAddFiletypes javascript_react.html
```

By the way, you asked where the ultisnips config is... You can either add this to your `.vimrc` (after the lines that load your plugins) or somewhere like `after/plugin/ultisnips.vim`. Personally, I would do the later in the interest of being organized. Any `*.vim` file you place in `after/plugin` will be evaluated after your config is done being executed.
