### ISSUE TITLE
Refactoring Javascript / Typescript snippets files (snippets folder)

### ISSUE THREAD

**Issue by yatoogamii** [honza/vim-snippets#1264]
Hello !

I want talk about 3 little things.

# First 

[javascript-es6-react.snippets](https://github.com/honza/vim-snippets/blob/master/snippets/javascript-es6-react.snippets)  and [javascript-react.snippets](https://github.com/honza/vim-snippets/blob/master/snippets/javascript/javascript-react.snippets) files are almost the same.

javascript-es6-react is the 'most' deprecated file. Included no hooks and use PropType now [discourage by react team](https://reactjs.org/docs/static-type-checking.html) instead of Typescript. But it has a good notation about snippet

javascript-react file include Class component / functionnal component methods, Hooks and PropType.

I propose to keep javascript-react file and remove javascript-es6-react. I already merged into my fork the 2 files and keep the better of each files.

# Second

We have some Javascript snippets inside and outside Javascript folder. Can we merged all into javascript folder ? To keep maintenability and readibility better.

# Third

We have actually 2 snippets file for Typescript (but possibly more in the future, i think about Vue and Deno). Can we create Typescript folder ?

**Comment by lpil** [comment]
It would be good to revive outdated snippets for sure!

RE the folder it would be preferable to move snippets out of the folder rather than into it. Library snippets are not supposed to be enabled by default according to our policy, so the JavaScript ones are breaking that rule at the moment.
