### ISSUE TITLE
Duplicate sum in latex snippets

### ISSUE THREAD

**Issue by vcoyette** [honza/vim-snippets#1266]
Hi,
There are two snippets 'sum' in snippets/tex.snippets. They are not exactly the same, but very similar, I think one of them should be renamed (summ for the summation?) or deleted.

**Comment by lpil** [comment]
I think you are right. Please open a pull request fixing the issue if you have the time. Thank you

**Comment by vcoyette** [comment]
Sure, which one do you prefer ? Delete or rename the second one ?

**Comment by lpil** [comment]
Rename sounds good to me. I don't mind what the name is though!
