### ISSUE TITLE
vim-snippets  reduced startup speed of neovim.

### ISSUE THREAD

**Issue by pittcat** [honza/vim-snippets#1267]
![vim-snippets](https://user-images.githubusercontent.com/22888402/94985976-736d4280-058d-11eb-8773-510821995dc2.png)

**Comment by pittcat** [comment]
It seems like that the startup speed of neovim turned into very slow after the commit , d4c285e8e7b482db810f453a308d45f259facbf9.

**Comment by lpil** [comment]
How long is it taking? Are you using the latest version?

**Comment by polyzen** [comment]
After the speedup commit it was taking about 15ms on one machine iirc, compared to gruvbox and vim-unimpaired which were around 9ms. Setting [these vars](https://github.com/polyzen/dotfiles/commit/ad10c90ad2425d442b0a411ec7e466201cf50526) brought it back down to well under 1ms.
