### ISSUE TITLE
Wrong Java "find" methods snippets

### ISSUE THREAD

**Issue by alexghergh** [honza/vim-snippets#1282]
Hello,

I feel like these snippets are wrong:

```
snippet findall
	List<${1:listName}> ${2:items} = ${1}.findAll();
snippet findbyid
	${1:var} ${2:item} = ${1}.findById(${3});
```
I think they should be:

```
snippet findall
	List<${1:listName}> ${2:items} = $1.findAll();
snippet findbyid
	${1:var} ${2:item} = $1.findById(${3});
```

Notice that the second one doesn't have braces around the second `$1`.

The first one puts you straight to the second `$1`. I do not know why that works like that, but that's what happens.

If someone can confirm this is indeed a typo/issue/bug, I would be happy to take a look at the whole Java file and see if I can find other occurences of this.

**Comment by lpil** [comment]
I think you're right. Would you mind making a PR to fix this? Thank you
