### ISSUE TITLE
Wrong/duplicate snippets in snipMate/UltiSnips folders

### ISSUE THREAD

**Issue by alexghergh** [honza/vim-snippets#1284]
I couln't help but notice that some of the snippets are either duplicate or wrong in one or both of the snippets folders.

For example (in java snippets):

This snippet from `snippets` folder (snipMate format) is clearly wrong (by wrong I mean it doesn't do what you would expect it to do):
```
snippet set
	${1:public} void set${3:}(${2:String} ${0:}){
		this.$4 = $4;
	}
```

What one would expect to happen is if you type `set<insert-snippet-character>` it would go to:
```
{1}_public_ void set{2}(_String_{3} {2}) {
	this.{2} = {2};
}
```
I've marked with `{#}` the position in which the cursor jumps with `<Ctrl-j>` and with \_underline\_ the strings which are offered for completion but can be changed with presses of `<Ctrl-j>`.

Incidentally, this UltiSnips snippet does just that:
```
snippet /set(ter)?/ "setter" br
public void set${1:Name}(${2:String} `!p snip.rv = mixedCase(t[1])`) {
	this.`!p snip.rv = mixedCase(t[1])` = `!p snip.rv = mixedCase(t[1])`;
}
```
(Although arguably you might expect to be able to change `public` as well, though I see why in practice this might never happen).

This is just one example of duplicate/wrong snippets.

There are also snippets which simply repeat in both folders:
```
snippet j.i "java_io" i
java.io.
endsnippet
```
in UltiSnips format, and:
```
snippet j.i
	java.io.
```
in snipMate format.

So my question is this: why is this happening, is this historical reasons? (I can see that at some point they got merged, and you simply didn't bother to clear the duplicates). Are they of any use now? I don't really mind the duplicates (though they pollute the completion list), but the wrong snippets simply shouldn't be there?

Thank you

**Comment by lpil** [comment]
If there's something that generated invalid code then that's a mistake I think. Any PRs fixing snippets are gratefully accepted, thank you
