### ISSUE TITLE
How to use snippets in UltiSnips/ directory?

### ISSUE THREAD

**Issue by ultra-nexus** [honza/vim-snippets#1301]
I have tried `UltiSnipsAddFiletypes c` but it doesn't work. I even tried `cp UltiSnips/c.snippets snippets/` but vim will reports errors.

**Comment by lpil** [comment]
Hello! What snippet plugin are you using? The ultisnips directory should be automatically picked up by the ultisnips plugin

**Comment by ultra-nexus** [comment]
I use `SirVer/ultisnips`. Does this screenshot means `UltiSnips/` has been loaded?

![image](https://user-images.githubusercontent.com/73626347/103048532-e1903700-45c9-11eb-9803-94738aafaeec.png)

Actually, I'm finding a way to achieve this.

![](https://camo.githubusercontent.com/858d1f6329a29afd878bc9e6c2e024f5b989391a3ad70d3923c935a703c5b75b/68747470733a2f2f7261772e6769746875622e636f6d2f5369725665722f756c7469736e6970732f6d61737465722f646f632f64656d6f2e676966)

When he inputs `echo`, the snippet expand to a `print` statement and when he types `a`, `b`, `c`, the format-string `a: %r`, `b: %r`, `c: %r` are inserted automaticlly. I think this is extremely powerful. It seems that this `echo` snippet is not included in `vim-snippets`.

**Comment by lpil** [comment]
It looks like it works for you there. If you would like to contribute snippets they would be welcomed, though I believe Python now has string interpolation so that echo snippet is no longer so useful.
