### ISSUE TITLE
auto-completion of markers within a snippet doesn't work anymore

### ISSUE THREAD

**Issue by AdrienLemaire** [honza/vim-snippets#1308]
Hi,

using the react hook `useS` [snippet](https://github.com/honza/vim-snippets/blob/87dbbc69a4e540e65f2f653aa3617cc3b7562663/UltiSnips/javascript_react.snippets#L17)

```vim
snippet useS "useState Hook" b
const [${1}, set`!p snip.rv=t[1].title()`] = useState(${3:"${4}"})
endsnippet
```

Normally, when I'm on top of `${1}` and typing something, the `!p snip.rv=t[1].title()` would also copy the text that I'm writing.

It is not working anymore
```diff
-  const [isMobile, setIsMobile] = useState("")
+  const [isMobile, set] = useState("")
```

And I have no idea how to debug this.
All I can see from `:CocOpenLog` is 

```
2021-01-07T12:04:29.006 INFO (pid:3165370) [completion-complete] - Results from: around,buffer,word,snippets,tag
```
`:messages` doesn't return anything.

Using vim-snippets master@6159e8e, coc-snippets v2.3.1  and NVIM v0.4.4

**Comment by lpil** [comment]
Hi @AdrienLemaire ! This would be an issue to open in the coc-snippets project, we don't have any control over the expansion of snippets by snippet engine plugins. Thank you
