### ISSUE TITLE
How to get TeX snippets to work?

### ISSUE THREAD

**Issue by bgergely0** [honza/vim-snippets#1314]
Hello, 
I'm new to vim, and trying to set up snippets. 
I use UltiSnips with this repo, and most languages work fine, but i cannot get tex snippets to work (no tex snippets expand to code). Any ideas why? Is there something I should've set up? 
Btw, I import the repos with Plug, but I don't think it has to do much with the problem.

**Comment by lpil** [comment]
It should work automatically so long as the filetype of the buffer is the right language for the snippets you want to use.

Your can check by running `:set filetype?`

**Comment by bgergely0** [comment]
Thanks!
That was the issue. But what still is weird, that when I create a new .tex file with vim, the filetype is plaintex. Is there a way to make it tex, without manually running `set filetype=tex` ?

**Comment by lpil** [comment]
I'm not sure, sorry!

**Comment by bgergely0** [comment]
Looks like that part is managed by a different plugin.
Thanks for the help!
