### ISSUE TITLE
fortran snippets 

### ISSUE THREAD

**Issue by rudrab** [honza/vim-snippets#1319]
Hi,
I am a fortran programmer. 
I have found there is no fortran snippets here. I have created an Unltisnips snippets (as a part of my fortran plugin https://github.com/rudrab/vimf90). 

How I can submit that for your review and possible inclusiion?

**Comment by lpil** [comment]
Hi @rudrab ! New snippets are welcome but I am a little confused by your statement that are not fortran snippets, we have them here: https://github.com/honza/vim-snippets/blob/master/snippets/fortran.snippets

**Comment by rudrab** [comment]
@lpil this is for snipmet. There is none for Ultisnips, actually.

**Comment by lpil** [comment]
Ultisnips reads snipmate format snippets, so that's the preferred format unless some ultisnips only functionality is needed (i.e. Python scripting)
