### ISSUE TITLE
remove default value "body" for conventional commits

### ISSUE THREAD

**Issue by FabianUntermoser** [honza/vim-snippets#1337]
Hi there,
first thank you for this addition. I agree a good commit style should be practised.
However I noticed a small user experience problem, when using the new conventional commit templates.

In small projects, most of the time, I create one-line commit messages.
In the commit window (I use fugitive), I typically write `feat<TAB>` to expand the snippets.
However, as there is a default value "body" on every snippet, I additionally have to tab through and delete the body text if I only want a single line commit.

The problem would be solved, if you would keep the jump to the body section but leave the default value blank.
Would appreciate it, thanks!

**Comment by lpil** [comment]
That sounds like a good improvement. Would you be up for making a pull request?

**Comment by FabianUntermoser** [comment]
Alright I'll look into it.

**Comment by FabianUntermoser** [comment]
@lpil Hi! I created a PR. Mind looking into it?

**Comment by lpil** [comment]
Fab, thank you!

**Comment by FabianUntermoser** [comment]
No problem :)
First PR here we goo :tada:
