### ISSUE TITLE
tex: does not expand with $ infront

### ISSUE THREAD

**Issue by lkjell** [honza/vim-snippets#1340]
Hi,

in commit: 0f290ce487d8e65a1f3f7dabc8b0b045ca11ea95

when you write `$frac` and expand it will become `$frac{}{}`
but current main branch it is not possible to expand. There must be a white space between $ and frac

snip engine is ultisnip

edit:
I figured the problem. The said snippet for ultisnip is remove, however the snippet for is still present in snippets/tex.snippets.

**Comment by lpil** [comment]
Hello! Thanks for the report. If you have found a fix would you mind submitting a pull request? Thank you

**Comment by lkjell** [comment]
I could, but the snippets in ultisnips format were removed for a reason. Perhaps it was removed because ultisnips is able to read snipMate format and someone felt duplication of snippets is unnecessary. Let's hear the ultisnips guys first if they can fix it.

**Comment by SirVer** [comment]
This could be attributed to an incompatibility in UltiSnips expansion strategy versus snipMates. It was fixed in https://github.com/SirVer/ultisnips/commit/b974a13328071de45a85c62ab65c8bfed0142728. Thanks for bringing this to my attention!
