### ISSUE TITLE
Tex: New snippet for fraction is too intrusive

### ISSUE THREAD

**Issue by cristobaltapia** [honza/vim-snippets#1391]
The snippet defined [here](https://github.com/honza/vim-snippets/blob/master/UltiSnips/tex.snippets#L352#L354) (see below) inserts a fraction (`\frac{ }{ }`) every time that the `/` (slash) is used. This is a symbol that is commonly used also outside of the mathematical scope and should not autotrigger without asking (e.g. when writing a file path). If it is OK for you, I would propose to either remove it or make it aware of the math context before it autotriggers.

```snip
snippet / "Fraction" i
\\frac{${VISUAL}}{$1}$0
endsnippet
```

**Comment by lpil** [comment]
Let's remove it. Would you like to make a PR @cristobaltapia ?

**Comment by cristobaltapia** [comment]
Already done :)

**Comment by mowgli** [comment]
Sorry, Should have done a pull before.

Thanks
