### ISSUE TITLE
the "pac" in  tex.snippets is reduplicative

### ISSUE THREAD

**Issue by hanqing0521** [honza/vim-snippets#1404]
There are two "pac" for tex snippets to expand `\package[]{}`
```
vim-snippets/UltiSnips/tex.snippets:424)
vim-snippets/UltiSnips/tex.snippets:449)
```

**Comment by cxr6548** [comment]
In commit 457362e the message states that the more verbose of the two (the one with the regex stuff) it removes the square brackets entirely if options is backspaced. I propose adding a comment explaining this right next to it then removing the other.

**Comment by cxr6548** [comment]
Can this issue be safely closed?

**Comment by hanqing0521** [comment]
OK, thanks! It works well.
