### ISSUE TITLE
Autoexpand of frac Ultisnips snippet

### ISSUE THREAD

**Issue by urbainvaes** [honza/vim-snippets#1410]
First, many thanks for the great plugin!

I am not convinced by the new \frac Ultisnips snippet. Specifically, the auto-expand behavior is undesirable when writing text, for example when typing the word "fraction". Since there is no way to let Ultsnips know whether a word is typed in math mode or not, I think it would be better to revert the change to the old behavior.

**Comment by smjonas** [comment]
I think this was already fixed in the last commit! :) The autotriggger should be removed once you update.

> Since there is no way to let Ultsnips know whether a word is typed in math mode or not

By the way, this is actually possible in UltiSnips by using custom context snippets! For examples see https://github.com/gillescastel/latex-snippets/blob/master/tex.snippets.

**Comment by urbainvaes** [comment]
Ah that's great, thanks! :)

I didn't know math-only snippets were possible, this is very cool!
