### ISSUE TITLE
Display math adds a period

### ISSUE THREAD

**Issue by cxr6548** [honza/vim-snippets#1411]
Line 219 of tex.snippets
```
snippet dm "Display Math" w
\[
	${1:${VISUAL}}
.\]$0
endsnippet
```
Is this intentional?

**Comment by pilgrimlyieu** [comment]
Actually, this snippet may come from [How I'm able to take notes in mathematics lectures using LaTeX and Vim - Castel](https://castel.dev/post/lecture-notes-1/#inline-and-display-math).

> The snippet for displayed math is more simple, but it also is quite handy; it makes me never forget ending equations with a period.
