### ISSUE TITLE
This lll snippets is very annoying when one is filling the second arg of a tabular environment.

### ISSUE THREAD

**Issue by Aster89** [honza/vim-snippets#1476]
Given

https://github.com/honza/vim-snippets/blob/1049d2425b6d270621b48e110de37d5467a2a621/UltiSnips/tex.snippets#L387-L389

I'm not able to write `llllll` in a `\begin{tabular}{ here }`. I think a better trigger should be used.

**Comment by Aster89** [comment]
@jimmy-zx , since you're the last one who edited this file, would you please give your opinion on this?

**Comment by smjonas** [comment]
Maybe we can remove the autotrigger option from this snippet entirely?

**Comment by jimmy-zx** [comment]
Removing the `ell` auto trigger seems fine to me. Also, maybe we need some guidelines about auto triggers.

**Comment by Shane-XB-Qian** [comment]
hello there, would you mind check #1486 would you help check and/or remove it?
