### ISSUE TITLE
How to cope with UltiSnips and snipmate issues?

### ISSUE THREAD

**Issue by MarcWeber** [honza/vim-snippets#363]
Historically UltiSnips (depending on Vim with Python) introduced UltiSnippets and Snipmate introduced "snippets" files. Today UltiSnips can read both, but snipmate cannot. UltiSnips has "advanced" features which are useful in some cases such as "nested snippets" and special triggers - Marc Weber never felt need for special triggers in snipmate because it historically had snippet completion while triggering - and passing arguments to snippets by trigger can be emulated by input() which requires hitting <cr> one additional time. Thus which features are worth having or not depends heavily on the judgment of the user.

The big question now is: How should vim-snippets cope with it? Nice habits to keep in mind:
- prevent duplication (do it once)
- please users as much as possible

The most simple strategy could be:
- Put simple snippets in .snippets files
- If you have complex advanced alternatives think use UltiSnips files
  judgment of this idea:
- least snippet duplication
- it serves everybody as much as possible, duplicates can be "ignored" by telling engines to use first hit and making sure engines read the .snippet files first
- UltiSnips users have to open and look at two files

This is Marc Weber's favorite solution for now. One example following this is "html_minimal" example.

Please use this issue to discuss alternative solutions emphasizing on why they are better/worse than what I'm proposing above (which is already documented in the README).

If you're fine with the proposal only reply if  it looks like the thread comes to a different solution. I'd suggest waiting for about 4 weeks for people to put their opinions.
There is no hurry. 

I commented here that I added those comments to the README:
https://github.com/honza/vim-snippets/pull/355

The first PR following this suggestion appeared shortly after:
https://github.com/honza/vim-snippets/pull/362

There is an additional issue: Snippet engines support multiple files anyway: Should there be a simple command which allows finding the file defining a snippet? A simple grep all snippet files being used would be enough probably (eg using grepadd or such). That would be trivial to implement.

**Comment by polyzen** [comment]
The consenus is to keep duplicates, no?:
> Generally I am fine with the proposed solution, however I think duplicates in UltiSnips should not be removed - when somebody started working on UltiSnips triggers it is possible that further development will happen on them that use US features - this is easier when they are all in one file.

The readme still has:
> Currently all snippets from UltiSnips have been put into UltiSnips - some work on merging should be done (dropping duplicates etc).

**Comment by Freed-Wu** [comment]
We can write some script to convert ultisnippets/snippets. It can help us enjoy enough snippets.
