### ISSUE TITLE
removing angularjs snippets.

### ISSUE THREAD

**Issue by RyanPineo** [honza/vim-snippets#370]
When I first made the pull request to add a few angularjs snippets it was unclear if it would be a good fit to put them in this repo.  The reason being that there is no way to distinguish a file using angularjs from any other javascript.

There are quite a lot of snippets that could be included for use with angularjs and I think because of that and the above reason they should be moved to their own repo.

In fact there is already a good repo for such snippets at https://github.com/matthewsimo/angular-vim-snippets.

Just my 2 cents.

**Comment by alexlafroscia** [comment]
Did a solution to the JS framework snippets ever get worked out?  The Ember snippets are pretty out-of-date, since the `App` global object really isn't a thing anymore.

**Comment by lpil** [comment]
Sadly not. I think we're currently leaning towards removing them from the Javascript namespace.

If the Ember snippets are out of date we should update or remove them.

**Comment by mmwtsn** [comment]
Perhaps we could open a few issues for updating the various JavaScript vendor snippets that are known to be outdated or lacking and assign a `needs-pr` label to them. I've found that's an easy way to flag low-hanging fruit for new contributors. Once the `javascript-vendor` directory is set up someone familiar with the framework or library should be able to jump in.

"Update the Ember.js snippets to version x.xx"
"Update the Angular.js snippets to version x.xx"

Et cetera.

**Comment by alexlafroscia** [comment]
@lpil I'm working on a larger-scale plugin from Ember development that will include plugins that are more appropriate for the Ember CLI.  Maybe it would make more sense to just remove them from here and direct people to another source for more specific snippets?

**Comment by lpil** [comment]
It would be nice to keep them in here as this repo is supposed to be a one-stop-shop for snippets. The problem is mainly with not polluting the top level namespaces with library snippets.

**Comment by alexlafroscia** [comment]
Is there a way for turn off library snippets? For example, I don't ever want any of the Angular snippets in my Ember projects.  Is it just a naming convention that ensures they aren't visible by accident?

**Comment by lpil** [comment]
It's purely the naming convention.

We should come up with a new one for snippets that belong to a format but are not to be loaded by default.

**Comment by mmwtsn** [comment]
How about this?

- Base language snippets are available by default (e.g. `javascript.snippets`)
- Additional library, framework, or legacy version snippets are available in a `<language>-vendor` directory (e.g. `javascript-vendor/angular.snippets`)
- Vendor snippets are not available by default but can be included by the user on a snippet-by-snippet basis as needed

Pull request opened here: #581

@alexlafroscia You can turn _on_ snippets (more on that in [at the end of #468](https://github.com/honza/vim-snippets/issues/468#issuecomment-104341784)). Not sure about turning them off.

**Comment by alexlafroscia** [comment]
@mmwtsn That sounds like a good approach to me!

**Comment by lpil** [comment]
Sounds like a good plan.

**Comment by SirVer** [comment]
I think this can be closed now that we have a way of dealing with vendor snippets.
