### ISSUE TITLE
Allow more control over loading of Javascript snippets

### ISSUE THREAD

**Issue by lpil** [honza/vim-snippets#468]
Hello all!

So lately I've been having a problem with the Javascript snippets. There's a great deal of library specific snippets (namely jQuery ones) that I'm uninterested in using, yet with the current directory structure there doesn't seem to be a way to prevent them from being loaded (as least as far as I can tell).

The issue is that because the directory is called Javascript all the contents will be loaded by vim-snipmate as they match `scope/*.snippets`, and if I change the scope from 'javascript' I lose the vanilla JS snippets too.

My first thought was to remove the `javascript/` directory and call them `javascript_jquery.snippets` etc in the parent dir, but this will have the same problem, as it also uses the search pattern `scope_*.snippets`.
If we used filenames that don't match either of these suddenly we have snippets that were loaded by default that no longer are, and I expect this would annoy users, so this probably isn't a good idea overall.

How do you deal with situations like these?

Cheers,
Louis

**Comment by mmwtsn** [comment]
From SirVer's above answer it sounds like creating a `UltiSnips` directory in `~/.vim/` and adding a snippet files there will give you the ability to add, remove, or modify snippets without having to modify the plugin files directly and risk losing your changes whenever the plugin is updated.

Is this documented anywhere?

I would like to disable the JavaScript Jasmine snippet file as [a snippet within that file](https://github.com/honza/vim-snippets/blob/b11832aa686e7cc18385110398ca4e8b5688b5d9/UltiSnips/javascript_jasmine.snippets#L45-L46) is conflicting with [a Node.js snippet](https://github.com/honza/vim-snippets/blob/4496631cf19dde58f3fc95b573637464ac1b7698/snippets/javascript/javascript.node.snippets#L4-L5) I use regularly.

Being able to opt in or out of individual snippets (perhaps by turning them off one by one in your `.vimrc` or turning off an entire language then explicitly requiring only the snippets you're interested in) would be great.

**Comment by lpil** [comment]
What an obnoxious set of snippets for a testing framework. One has a single letter trigger!

I'll open a PR to remove a bunch of these.

**Comment by SirVer** [comment]
> Is this documented anywhere?

Sure, in UltiSnips docs. 

> Being able to opt in or out of individual snippets (perhaps by turning them off one by one in your .vimrc or turning off an entire language then explicitly requiring only the snippets you're interested in) would be great.

This comes up from time to time. I suggest pulling them out from the javascript filetype and teach people how to use `:UltiSnipsAddFiletypes` in their config to pull in the snippets they like.

**Comment by mmwtsn** [comment]
| Sure, in UltiSnips docs.

Thanks. I missed that when initially reading through the docs. Adding a note in both the vim-snippets and UltiSnips README files might help as this question seems to arise somewhat frequently.

For anyone reading along at home you can associate additional snippets by name with any given filetype using the `:UltiSnipsAddFiletypes` command. More information can be found within the documentation (`:help UltiSnipsAddFiletypes`).

For example, if you wanted to make JavaScript snippets available in HTML files you would run the following: `

**Comment by SirVer** [comment]
I think this is fixed with the vendor approach.
