### ISSUE TITLE
Ultisnip CSS snippets currently have an extremely high amount of name duplication, and are of little use

### ISSUE THREAD

**Issue by lpil** [honza/vim-snippets#469]
https://github.com/honza/vim-snippets/blob/master/UltiSnips/css.snippets

Just look at that- it's mental. Even time you hit tab you have to spend a couple of seconds trying to work out which one you're after, by which point you may as well have just typed the whole thing. The `background` snippets are an excellent example of this- 10 snippets with the same name, lines 17 to 53.

The snippet names are all long, and half of them are not at all useful. I would like to remove almost all of them, and have people use the much more useful `snipmate` style `css` snippets, without all the noise from these ones.

One disadvantage to this is that we would then have no `scss` snippets for `ultisnips` users, though currently they're getting a pretty raw deal at the moment anyway. I've opened an issue to discuss this here: https://github.com/SirVer/ultisnips/issues/389

Cheers,
Louis

**Comment by hhu94** [comment]
Any follow up on this issue? I've recently started using UltiSnips and I really don't like the noise from all the snips with the same name.

**Comment by lpil** [comment]
Someone just needs to start tackling it. Pull requests are very welcome :)

**Comment by mrzool** [comment]
Maybe a *help-wanted* label on this issue might attract some attention?

**Comment by lpil** [comment]
Good suggestion. Thanks.

**Comment by jrock2004** [comment]
What's the goal of what you want done to the  css ones? I'll gladly do the work and help out but what do you want?
