### ISSUE TITLE
markdown snippets do not seem to load for markdown files

### ISSUE THREAD

**Issue by mmynsted** [honza/vim-snippets#517]
When I load a markdown file, i.e. one named `foo.md` or `bar.markdown`, I get correct markdown syntax highlighting but no markdown snippets from [honza/vim-snippets/UltiSnips/markdown.snippets](https://github.com/honza/vim-snippets/blob/master/UltiSnips/markdown.snippets).  

The following is defined in my `~/.vimrc`.
```vim
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'bonsaiben/bootstrap-snippets'
Plugin 'spiroid/vim-ultisnip-scala'
```

and 

```vim
augroup markdown
    au!
    au BufNewFile,BufRead *.md,*.markdown,*.mmd setlocal filetype=ghmarkdown
augroup END
```

and 

```vim
let g:UltiSnipsEditSplit="vertical"
let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 3
"let g:neocomplete#lock_buffer_name_pattern = '\*ku\*'

autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
```

The `lorem` snip works and I even see the `"Lorem Ipsum - 50 Words"` message when I use it so I am fairly sure it is loading from [here](https://github.com/honza/vim-snippets/blob/master/UltiSnips/all.snippets#L120).

**Comment by lpil** [comment]
```viml
au BufNewFile,BufRead *.md,*.markdown,*.mmd setlocal filetype=ghmarkdown
```

It looks like you're using a filetype called `ghmarkdown`, and I suspect that this is not the same as the `markdown` filetype.

Could you try explicitly loading the `markdown` snippets scope for me and see how that works?

I don't speak vimL, but I think something like this might be what you're after.

```viml
augroup markdown
    au!
    au BufNewFile,BufRead *.md,*.markdown,*.mmd setlocal filetype=ghmarkdown
    au BufNewFile,BufRead *.md,*.markdown,*.mmd UltiSnipsAddFiletypes ghmarkdown.markdown
augroup END
```

**Comment by lpil** [comment]
May I ask why you are using `spiroid/vim-ultisnip-scala`? :)

**Comment by mmynsted** [comment]
That fixed it.  Thank you.

> May I ask why you are using spiroid/vim-ultisnip-scala? :)

Because I am using `UltiSnips` and did not see scala in here [vim-snippets/UltiSnips/
](https://github.com/honza/vim-snippets/tree/master/UltiSnips), and thought the ones in  [vim-snippets/snippets/scala.snippets](https://github.com/honza/vim-snippets/blob/master/snippets/scala.snippets) could thus not be used. 

I just took it out and the scala snippets still work, so I guess that was not needed.

I think the next step will be to learn how to add my own.  Thanks again.

**Comment by SirVer** [comment]
UltiSnips reads all snippets in this repo, also the snipMate ones in `snippets/`. Closing this as it seems everything is resolved.
