### ISSUE TITLE
JavaScript Snippet for var f = function () {}

### ISSUE THREAD

**Issue by nybblr** [honza/vim-snippets#524]
I see a snippet for assigning a named function to a local variable, but none for the (more popular in my mind) anonymous function assignment to a local var. Is this intentionally omitted, or just in need of a PR? =)

I was thinking `vaf` might be appropriate (var anonymous function)?

**Comment by lpil** [comment]
As far as I understand, a named function assigned to a variable, and a named function assigned to a variable are equivalent, except the named one offers more debug information.

I suspect that assigned anon functions are more popular only because they require less typing- an advantage that vim-snippets removes.

Is there a reason why you would like an anon function assigned to a variable in this repo?

**Comment by nybblr** [comment]
var = anon is not just for terser syntax (although it is handy) :wink:

They are mostly equivalent, however there are some key differences:

- var anon help emphasize JavaScript's functional nature (invaluable when teaching)
- the named function pollutes the inner namespace with a shadowed function name, which can confusingly prevent the inner function reference from being changed (often the reverse is true) from the outside (e.g. recursion)
- in the not-so-contrived case that someone lops off the `var func = ` part and forgets a return statement or something similar, it will happily be converted to a function declaration rather than causing a linter to shriek at the unassigned anonymous function

Also, named functions aren't necessarily better for all uses:

- Most JS interpreters assign the variable name to the function for debug purposes
- When a function is reused on many objects, the intrinsic function name can shadow the (sometimes more useful) name/method name used in the context.

The debate on named function expressions vs anonymous is not "always do it this way," so I think a snippet would be worth adding (it takes a surprising amount of time to type one out, esp when parenthese matching gets in the way =)

**Comment by lpil** [comment]
Seems reasonable. Do you think it should replace the named `vf` snippet?

**Comment by nybblr** [comment]
I still find `vf` useful for constructors, and it'd be better not to break compatibility. I'd vote for a different shortcut, e.g. `vaf`

Will do!

**Comment by nybblr** [comment]
https://github.com/nybblr/vim-snippets/pull/1

**Comment by nybblr** [comment]
Let's try this again =) https://github.com/honza/vim-snippets/pull/525
