### ISSUE TITLE
Wrong lines in ruby.snippets

### ISSUE THREAD

**Issue by QVirus** [honza/vim-snippets#545]
I think this lines shouldn't be in ruby.snippets
```
snippet end
        __END__
```
Because it looks so strange
```
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
__END__
```
:-)

**Comment by lpil** [comment]
That snippet isn't valid Ruby there- why do you want to use it like that?

**Comment by QVirus** [comment]
@lpil you are right! This snippet isn't correct and must be remove from "ruby.snippet" (lines 39 - 40)

**Comment by lpil** [comment]
No, it is correct. `__END__` denotes the end of the source file, and the interpreter will no longer read any lower. It's another funky thing that Ruby inherited from Perl.

You can put whatever you want after that keyword. I once played with storing config data for a script in there, it worked OK.

**Comment by QVirus** [comment]
Ok! I understand you!
But...
If I type some code, like this:
```
class BuildingsController < ApplicationController
  def list
    @buildings=Building.all.order(:name).paginate(page: params[:page])
  end

  def new
    @building=Building.new
  end

  def create
    @building = Building.new(building_params)
    if @building.save
      flash[:success] = "Building created"
      redirect_to building_url(@building)
    else
      render 'new'
    end
  end
...
```
Why should I have hemorrhoids with end-to-__END__ translations each time when I type "end"? :-/

**Comment by lpil** [comment]
How come it's inserting `__END__` when you type `end`? What is triggering the snippet expansion?

**Comment by QVirus** [comment]
The snippet expansion triggering was "\\<CR>". I change it to another one... :)
Sorry, my friends, for my carelessness.
