### ISSUE TITLE
jekyll markdown support

### ISSUE THREAD

**Issue by xiaoronglv** [honza/vim-snippets#549]
a jekyll post head example

```
---
title: The top of my todo list
layout: post
guid: mnWbPAh2fbvR7E
date: 2015-02-20 09:41:25
tags:
   -
---
```

Many people use jekyll to write his blog. Could you add this snippet to markdown.snippets?

This snippet makes writing blog easily.

```
snippet head "Jekyll post header" b
---
title: ${1:title}
layout: post
guid: `!p
import uuid
if not snip.c:
  guid = uuid.uuid4().get_hex()
snip.rv = guid
`
date: `!v strftime("%Y-%m-%d %H:%M:%S")`
tags:
  - ${4}
---

${5}
endsnippet
```

**Comment by SirVer** [comment]
This snippet seems overly specific for general markdown. I suggest you keep this in your private snippets and/or make a new filetype in this repo for jekyll.

**Comment by xiaoronglv** [comment]
Thx for your reply.

I keep it in my private snippets ^_^
