### ISSUE TITLE
.tex snippets not working on empty files

### ISSUE THREAD

**Issue by henriqueleng** [honza/vim-snippets#552]
If I create a .tex file like $ vim test.tex. the snippets don't work, as it does with .c or .html files. I am running garbas/vim-snipmate, and It only work if I open a file already estructured with latex stuffs.
This gif explain better:
![out_optimised](https://cloud.githubusercontent.com/assets/7434647/6888815/ea41c1ec-d65e-11e4-83a7-3cdbb7c9dc2b.gif)

* The aids file is a biology work, not a joke.

**Comment by SirVer** [comment]
That sounds like your vim is not setting the `filetype` property. Could you check `:set filetype` in the two different files?

**Comment by ajzafar** [comment]
> That sounds like your vim is not setting the filetype property.

That's exactly what's happening. By default, Vim sets `ft=plaintex` for empty .tex files, which can be changed with `let g:tex_flavor = "latex"`. See `:h ft-tex-plugin`.

**Comment by henriqueleng** [comment]
setting let g:tex_flavor = "latex" solved the problem. Without this :set filetype was returning plaintex now it is returning filetype=tex
