### ISSUE TITLE
add behavior to snippets based on language syntax?

### ISSUE THREAD

**Issue by sandric** [honza/vim-snippets#566]
Is there a way for multiple snippets be responsible for one thing, but get chosen based on language syntax? For example for golang, there's one syntax for variables defining in global scope: 
```go 
var variable = 42
``` 
and different for the same inside of function definition: 
```go
variable := 42
```
For now it is different snippets with different shortcuts, is it possible for them to have one shortcut, but get pasted in code in respect to golang syntax - if it is global scope under the cursor - use first definition, if it is function scope - second?

**Comment by SirVer** [comment]
Vim has no concept of scope, so there is no easy way to get to this knowledge programmatically imho. If you can figure out a python expression that can get you to this information, you can (soon) use https://github.com/SirVer/ultisnips/pull/446 to do this in UltiSnips.

**Comment by sandric** [comment]
@SirVer actually, particularly in this example, you could do such a snippet, if there was option for "Insert snippet, if snippet keyword for expansion is placed at the beginning of the line, and there's no even whitespaces preceding" - like the `b` option, but more strict. Or there's a way for it I just don't see?

**Comment by seletskiy** [comment]
@sandric: After my PR will be merged, you will be able to make simple regular expression check that there is a function definition, preceeding snippet expansion.

I've tested this:

```
snippet x "global var definition" b
var $1 = $2
endsnippet

snippet x "local var definition" "[1 for l in buffer[:line-1] if re.match('^func ', l)]" be
$1 := $2
endsnippet
```

Actually, adressing this concrete issue you can use `r` flag to match snippet, which have no whitespaces before keyword.

**Comment by sandric** [comment]
Ok, I see its doable, for this example, thx, @seletskiy. Will close the issue then.
