### ISSUE TITLE
Some suggested snippets

### ISSUE THREAD

**Issue by voyeg3r** [honza/vim-snippets#569]
# I am lefting here some suggested snippets

snippet sh
	#!/bin/bash
	# Created: `system("date +%d-%m-%Y")`
	# Last Change: `system("date +%d-%m-%Y")`
	# vim:ft=sh:fdm=syntax:nu:
	# company: ${1:<+instituicao+>}
	# This script aims: ${2:<+descricao+>}
	# Author: ${3:<+autor+>}
	# site: ${4:<+site+>}

# check if dir exists
snippet ifdir
	[ -d ${1:namedir} ] || mkdir $1 ; cd $1
	${2:echo}

snippet ifile
	if [ ! -e "${1:filename}"  ]; then
		echo "  file \"$1\" not present"
	fi
# the two following snippets compare two given vars
snippet gt
	if [ ${1:$var} -gt ${2:$other} ]; then
		echo 'Bigger than $2'
	else
		echo 'Smaller than $2'
	fi
snippet lt
	if [ ${1:$var} -lt ${2:$other} ]; then
		echo 'Smaller than $2'
	else
		echo 'Bigger than $2'
	fi

snippet ir
	# Check if root is logged in
	if [ "$(id -u)" != "0" ]; then
		echo "  Need be root"
		sleep 2
		exit  1
	fi

# sets a lock file 
snippet lock
	LOCK_FILE=/tmp/.lock
	(set -C; :  > $LOCK_FILE) 2> /dev/null
	if [  $? != "0" ];  then
		echo "Lock File exists - exiting"
		sleep 1
		exit 1
	fi

**Comment by SirVer** [comment]
please make a pull request instead.
