### ISSUE TITLE
Missing snipmate C snippets while editing CPP file with UltiSnips

### ISSUE THREAD

**Issue by hickop** [honza/vim-snippets#577]
Looks like I'm missing some basic snippets in UltiSnips.
For example "if" will not trigger and is only defined in snippets/c.snippets.

**Comment by SirVer** [comment]
UltiSnips is not parsing the 'extends' keyword for snipMate snippets.

That was a feature that was not yet implemented when I wrote the support for those snippets into UltiSnips. Nobody has backfilled that when snipMate started supporting it. Not a vim-snippets bug though, so I'll close it.
