### ISSUE TITLE
load helper functions

### ISSUE THREAD

**Issue by albfan** [honza/vim-snippets#583]
Hi, I'm tweaking some snippets and need some help

I managed to create my first snippet, but it uses a helper function (vimL) and don't know where is the standard path to put that helper functions.

e.g (package autocompletion on java files)

```viml
snippet pa "package" b
package ${0:`!v UltiSnips_Java_GetPackage()`}
endsnippet
```

So, where should I put 

```viml
function! UltiSnips_Java_GetPackage()
```

**Comment by SirVer** [comment]
Wherever you want, basically. Vim does not have the concept of namespaces, so you just have to make sure that the function is defined as soon as you run the snippets. One place where you might want to put it is in your `.vimrc` or in a `ftplugin/java.vim` file that is sourced for each java file.
