### ISSUE TITLE
continue on insert mode after completion

### ISSUE THREAD

**Issue by albfan** [honza/vim-snippets#584]
based on #583 example, another doubt is, how can I continue on insert mode after accept ${1} suggestion 

I have tried 

```viml
snippet pa "package" b
package ${1:`!v UltiSnips_Java_GetPackage()`} ${0}
endsnippet
```

but no luck

**Comment by lpil** [comment]
I'm not sure I understand. You should be insert mode when you hit `${0}`.

Could you go through what you do, including the keypresses.

What plugin are you using?

**Comment by albfan** [comment]
I have corrected the positional parameter. My mistake! I'm using UltiSnips.

You say that snippet should continue on insert mode?

given 

    src/main/java/my/package/myfile.java

```viml
UltiSnips_Java_GetPackage()
```

returns 

    my.package

so (| is cursor position)

pa&lt;TAB>|

should become

package my.package |

continuing on insert mode (if possible)

**Comment by lpil** [comment]
I can't replicate this, could you provide the function?

**Comment by albfan** [comment]
My mistake. I have to use "<c-j>" to go to next position. Why not tab works as "go to next positional parameter"? is that possible?

**Comment by SirVer** [comment]
@albfan Yes, you can use the same trigger in your configuration, but it is almost certainly going to surprise you in everyday use. I was fed up with the bug reports that caused and took that out of the documentation. Please read through https://github.com/SirVer/ultisnips/issues/305 before attempting this.

**Comment by lpil** [comment]
Your experience may vary- I use tab for both with Ultisnips and generally I don't encounter any problems. Just have to be a little careful with what words you pick to trigger snippets.
