### ISSUE TITLE
Add a test that checks validity of all snippets

### ISSUE THREAD

**Issue by lpil** [honza/vim-snippets#587]
It'd be great to know that our snippets actually work. Is there a good way to ensure that our snippets are in a valid format that doesn't cause ultisnips etc to throw an error?

**Comment by SirVer** [comment]
See what I wrote in https://github.com/honza/vim-snippets/pull/586. I do not think it is worth the effort.

**Comment by lpil** [comment]
Seems reasonable. Thanks for your opinion. :)
