### ISSUE TITLE
Double quotes in Ruby snippets

### ISSUE THREAD

**Issue by juanibiapina** [honza/vim-snippets#595]
How do you feel about changing all strings in ruby snippets to use double quotes? I can make the pull request, but want to make sure you're on board.

**Comment by taq** [comment]
I like more the double than the single because you don't even need to think if you're using some interpolation or not, but the single quotes are the default way on the Ruby style guide, so ...

When using [rubocop](https://github.com/bbatsov/rubocop), you can have a warning like "Prefer single-quoted strings when you don't need string interpolation or special symbols." when using double quotes.

**Comment by juanibiapina** [comment]
I agree with your opinion on the quotes.

I also think both rubocop and the style guide are misguided.

**Comment by juanibiapina** [comment]
Check this link: http://anti-pattern.com/water-your-controllers-they-are-too-dry

**Comment by taq** [comment]
Yeah, but the style guide still is **the** style guide, one way to abstract all the opinions. If we change here to double quotes, I bet a lot of folks who live by the style guide wlll complain. And they will have one more point than us. 

So, I think it's more productive to question the style guide (and rubocop) about this than to start here and became the different ones. :-)

**Comment by juanibiapina** [comment]
Yep, already commented there, my bad.

On Tue, Jul 7, 2015 at 3:29 PM, Eustáquio Rangel <notifications@github.com>
wrote:

> Yeah, but the style guide still is *the* style guide, one way to abstract
> all the opinions. If we change here to double quotes, I bet a lot of folks
> who live by the style guide wlll complain. And they will have one more
> point than us.
>
> So, I think it's more productive to question the style guide (and rubocop)
> about this than to start here and became the different ones. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/honza/vim-snippets/issues/595#issuecomment-119293688>.
>



-- 
Juan

**Comment by taq** [comment]
No problem! Maybe (really) we can ask for a style guide revision. I'll check this later.

**Comment by juanibiapina** [comment]
It seems the maintainer of the guide is not willing to change this guideline: https://github.com/bbatsov/ruby-style-guide/issues/184

I'll just drop rubocop from my project and stick to the github style guide. Probably fork this repo and make the quote changes there.

**Comment by taq** [comment]
Ok!

**Comment by juanibiapina** [comment]
I'll leave the link here just in case: https://github.com/juanibiapina/vim-snippets
