### ISSUE TITLE
"set paste" breaks snippet triggering

### ISSUE THREAD

**Issue by xliiv** [honza/vim-snippets#608]
Having this settings
```
set paste
```
in `.vimrc` breaks snippet triggering in non-gui vim.

**Comment by lpil** [comment]
This should probably be an issue in whatever snippet plugin you're using, we only maintain snippets here :)

**Comment by xliiv** [comment]
Stupid me :), I'll leave a trace here in case someone else goes wrong
https://github.com/SirVer/ultisnips/issues/403

**Comment by lpil** [comment]
Good luck finding a solution!

**Comment by SirVer** [comment]
Just to clarify: `set paste`'s purpose is kinda to break all snippets and all settings. See `:help paste'.
