### ISSUE TITLE
Vim function Filename used Ultisnips snippet pandoc.snippets no available anymore

### ISSUE THREAD

**Issue by Hans-Guenter** [honza/vim-snippets#617]
The function Filename used in Ultisnips/pandoc.snippets is not available anymore.
Therefore the snippet line

% ${1:`!v Filename(' ', 'title')`}

has to be replaced by

% ${1:`!v vim_snippets#Filename('$1', 'title')`}

**Comment by SirVer** [comment]
Closed by #618
