### ISSUE TITLE
AngularJS (snipMate) Snippets

### ISSUE THREAD

**Issue by jasonsjones** [honza/vim-snippets#627]
Hi,

Recently I've been using a snippet file (snipMate format) I created supporting the basic
AngularJS components that follow John Papa's popular [style guide](https://github.com/johnpapa/angular-styleguide)

I was a little surprised to not see any snippets for AngularJS in snippets/javascript/.  However, I acknowledge my snippets (and thus the style guide) are a bit opinionated, which is why I'm wanting to double check here to see if there would be interest in the snippets before I make a pull request.

The file contains snippets for AngularJS module, Controller, service, factory, directive, and filter.

Let me know and I can make the PR.  Thanks for all the great work!

**Comment by SirVer** [comment]
we have other vendor snippets in the repo. I do not see why we should not have angular as well. They should not be enabled by default though, see the vendor section in the readme.

**Comment by jasonsjones** [comment]
Thanks Holger.  I looked at the vendor section of the README and it appears there is only information on disabling UltiSnips snippets; no mention of how to disable by default snipMate snippets.  When I get some more free time, I'll dig around in the snipMate documentation to see what I can find, if it is even possible to disable snippets on a per file basis.  If I can find a way to disable by default, I'll open a PR.  

BTW, I concur wholeheartedly with disabling by default--don't want to clobber the js namespace if folks are not interested, although the likelihood of a snippet name collision is very low if they are not working with Angular (all my snippets start with 'ng' by convention).  If I can't find a way to disable snipMate snippets by default, well...might be time to switch to Ultisnips ;-)

Also, if I find something helpful on the snipMate side, I'll update the README to improve the documentation for vendor snippets as they pertain to snipMate snippets.  Thanks again.

**Comment by SirVer** [comment]
That sounds great! Thanks, Jason.

**Comment by jasonsjones** [comment]
Just wanted to follow up on this issue since I had mentioned that I would take a look at the snipMate documentation and see if it was possible to disable specific snippet files by default.  Well...I've rather busy with work lately, so I didn't get too much time to dig around in the docs.  The time I did spend looking, it wasn't completely obvious to me on how to do it; however, that is not to say that it is not possible-- I was just not able to locate the correct plugin setting.  That said, I'm going to go ahead and close the issue.

In the process, I've also been checking out Ultisnips, and I must say, I think it fits my requirements much better that snipMate.  I like the extensibility, specifically the shell scripting and vimL scripting integration.  So, Holger, I think you may have just converted me to a Ultisnips user ;-)  And since that is the case, this issue is now OBE (at least for me anyway...), which is just another reason to close the issue. [OBE = overcome by events]  Thanks again for all the great work here and on Ultisnips--it is greatly appreciated!

**Comment by SirVer** [comment]
glad you like UltiSnips. Spread the word.
