### ISSUE TITLE
box and fold snippets from all.snippets return wrong comment format

### ISSUE THREAD

**Issue by Liberko** [honza/vim-snippets#629]
_get_comment_format() which is used in box, bbox, fold, foldc and foldp returns "-" mark instead "#".

**Comment by Liberko** [comment]
this issue occurs with editing .snippet files and using box, bbox, fold and foldc

**Comment by lpil** [comment]
Also `.sh` files.

**Comment by SirVer** [comment]
Should be fixed now. thanks for reporting.

**Comment by lpil** [comment]
Awesome, thanks guys.

**Comment by Liberko** [comment]
Thanks. BTW there are one more issue with this case now, `fold` snippets referring to non-existent `_get_comment_format()`.
>NameError: name '_get_comment_format' is not defined

**Comment by SirVer** [comment]
Ah, messed that up, sorry. Fixed in ac7fc9b5691ce751c0a2d54219bbc0a3fe46d9e4.

**Comment by Liberko** [comment]
Looks good, thanks!
