### ISSUE TITLE
Cross-filetype Snippets (i.e. HTML inside JS file)

### ISSUE THREAD

**Issue by indiesquidge** [honza/vim-snippets#644]
First off, I just want to thank all the contributors for this repo. The snippets are great and have saved me a ton of time as well as taught me how to write some of my own.

I have recently started writing some JSX files for a React application, and one thing I would really love to have access to is the `HTML` snippets inside of my `JavaScript` files. Is there any way to make this happen other than manually copy-pasting the snippets file for `HTML` into the snippets file for `JavaScript`? If that is the only way to get this then that's fine. I just wanted to make sure before going down that path.

Thanks,
Austin

**Comment by lpil** [comment]
Most snippet plugins allow you to load snippets from other formats. See the readme for details

**Comment by indiesquidge** [comment]
Thank you, @lpil. I apologize for not seeing it in the readme. For anyone else looking for it, [here's the link](https://github.com/honza/vim-snippets#vendor-snippets).

**Comment by lpil** [comment]
Happy to help :)
