### ISSUE TITLE
Retiring as maintaner here

### ISSUE THREAD

**Issue by SirVer** [honza/vim-snippets#645]
Posting here for visibility, since it is relevant to the project. 

@honza @lpil Guys, I need to get back some free time, so I am cutting down on my OSS commitments. I will not be available as a maintainer for vim-snippets going forward. I am going to disable notifications for issues and pull requests, so I won't even know that there is work to do.

If there are UltiSnips related questions, always feel free to pull me in via a mention. 

This project is awesome and the snippets in it are immensely useful. It also continues to help grow UltiSnips which I am very grateful for. See you around :)

**Comment by lpil** [comment]
Thanks for all your work Holger, good luck with the future! :)

**Comment by honza** [comment]
@SirVer Thank you for your work, it was an honor to have you contribute. :sparkles:

**Comment by iurifq** [comment]
Thanks for the work @SirVer. Enjoy your recovered time :wink:
