### ISSUE TITLE
box and bbox snippets not working correctly in python

### ISSUE THREAD

**Issue by cbaumhardt** [honza/vim-snippets#649]
Hi,

for me the `box` and `bbox` snippets (defined in `all.snippets`) don't really work in a python document. When I open a new buffer `test.py` (filetype is set automatically to python) and enter in insert mode `box<Tab>` I get the following result:
```python
# # ###########
#   content  # 
# ############ 
```
The same is true for the `bbox` snippet:
```python
# # ####################################################################
#                               content                               # 
# ##################################################################### 
```
I am not sure if I am making a mistake somewhere along the line. I am using UltiSnips in case that matters.

**Comment by lpil** [comment]
Same in Ruby and Elixir, which share the same commentstring.

**Comment by yannack** [comment]
This depends on the actual commentstring you have.
As a workaround, you may go to pythonx/vimsnippets.py and apply the following patch:
```
--- a/pythonx/vimsnippets.py
+++ b/pythonx/vimsnippets.py
@@ -68,7 +68,7 @@ def get_comment_format():
     """
     commentstring = vim.eval("&commentstring")
     if commentstring.endswith("%s"):
-        c = commentstring[:-2]
+        c = commentstring[:-2].strip()
         return (c, c, c, "")
     comments = _parse_comments(vim.eval("&comments"))
     for c in comments:
```

However, this may make commented lines on other generic snippets miss a space after the comment symbol. It does fix the box and bbox issue. The issue stems from the fact that the commentstring is:
`'# %s'` (note the space after the #).
Ideally, the commentstring would be stripped in the snippets for box and bbox though when getting the commentformat.

**Comment by yannack** [comment]
I just modified my comment to actually include a good fix. This should be OK for most cases.

**Comment by yannack** [comment]
Fixed in PR: https://github.com/honza/vim-snippets/commit/63bd097393e1c49528d0be3d798f7248b5497ccd

**Comment by honza** [comment]
PR merged, thanks
