### ISSUE TITLE
box and bbox don't work in in C/C++

### ISSUE THREAD

**Issue by themightyoarfish** [honza/vim-snippets#659]
When filetype is `c` or `c++`, the `box` snippet produces something like this

```
-------------
-  content  -
-------------
```

which is obviously a syntax error.

**Comment by davidszkiba** [comment]
Just tested this in both `c` and `c++` files and can't reproduce it. For me, the content looks okay. I guess this can be closed?

**Comment by lpil** [comment]
Thanks :)

**Comment by themightyoarfish** [comment]
Could anyone point me to how to debug this problem? What determines the comment character used? I still experience this issue.
