### ISSUE TITLE
Ruby snippets: Allow the user to specify whether they want single or double quotes

### ISSUE THREAD

**Issue by lpil** [honza/vim-snippets#677]
Unsure how we would implement this.

**Comment by juanibiapina** [comment]
I was maintaining a fork of this project where I replaced single quotes with double quotes in all ruby snippets, but this is a painful way to go about it. Here is the original fork: https://github.com/juanibiapina/vim-snippets

And the original discussion: #595 

I would also love to have that implemented somehow.

**Comment by honza** [comment]
I think this would have to come from the engine itself.

**Comment by lpil** [comment]
With ultisnips we could use a variable in place of quotes in the snippet definition. It would be super ugly.

**Comment by juanibiapina** [comment]
I'm back to this. Why ugly?

**Comment by lpil** [comment]
Ugly is probably the wrong word, just quite verbose. :)

**Comment by taq** [comment]
The eternal discussion between single and double quotes. :-) On one side the "just one key" and on the other the "don't think" arguments. Even Rubocop gets confused with that sometimes. 
I use to use single quotes and doubles only with interpolation, but I just loved the idea to have a way to the user decide about that.
