### ISSUE TITLE
Allow users to specify whether they want double or single quotes

### ISSUE THREAD

**Issue by lpil** [honza/vim-snippets#682]
The Ruby and Javascript languages seem like they would benefit from this.

The user could set a flag to indicate which to use.

```viml
let g:snips_ruby_quote="single"
let g:snips_javascript_quote="double"
```

**Comment by shepherdsam** [comment]
I'd use this for sure.

**Comment by juanibiapina** [comment]
Duplicate of #677 , so I've added my two cents there.
