### ISSUE TITLE
Enable ES6 

### ISSUE THREAD

**Issue by IonicaBizau** [honza/vim-snippets#690]
I spent about 30 minutes to understand how should I enable the ES6 snippets. :joy: Still couldn't achieve this.

If write `function` and press <kbd>Tab</kbd> twice, it generates this for me:

![image](https://cloud.githubusercontent.com/assets/2864371/13522640/4a40ffee-e1f9-11e5-939a-a5a5da35c8f9.png)

But if I write [`af`](https://github.com/honza/vim-snippets/blob/master/snippets/javascript/javascript.es6.snippets#L19-L22) and press <kbd>Tab</kbd> it does *not* generate the arrow function.

Somehow I have to include that `es6` file, but I have no idea how...

**Comment by lpil** [comment]
See the README :)

https://github.com/honza/vim-snippets#vendor-snippets

**Comment by IonicaBizau** [comment]
@lpil I did read all these!

![image](https://cloud.githubusercontent.com/assets/2864371/13522955/194a4092-e1fb-11e5-9871-a6f20580e610.png)

**Comment by lpil** [comment]
Are you using ultisnips?

**Comment by IonicaBizau** [comment]
@lpil Oh, that's the problem. I just added `Plugin 'SirVer/ultisnips'` in my `.vimrc`. For some reason, when I'm inside of `vim` I can run `:UltiSnipsAddFiletypes javascript-es6`, but if I put` UltiSnipsAddFiletypes javascript-es6` at the end of my `.vimrc` file, I'm getting the *Not an editor command* error. Why?

Thanks!

**Comment by IonicaBizau** [comment]
`autocmd FileType js UltiSnipsAddFiletypes javascript-es6` did the trick.
I got some inspiration from @saurabh-hirani's [`.vimrc`](https://github.com/saurabh-hirani/dotfiles/blob/master/.vimrc). Thanks! :cake:

**Comment by lpil** [comment]
Great! Glad you got it sorted. If you think the docs can be improved submit a pull request. :)
