### ISSUE TITLE
Snippets after parentheses

### ISSUE THREAD

**Issue by IonicaBizau** [honza/vim-snippets#692]
I want to get something like this:

``` js
[1, 2, 3].map((current, index) => {
  /* do something */
});
```

So, I write: `[1, 2, 3].map(af` or (`...map(=>`) and press <kbd>Tab</kbd>. The snippet is not working.
If I add a space after `map(`, it will work, but it will keep the space there: `[1, 2, 3].map( (current, index) => ...);`.

Is this easily fixable?

**Comment by app** [comment]
AFAIK snipmate format snippets do not support this feature https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L676-L730

You have to use UltiSnips snippets. https://github.com/honza/vim-snippets/tree/master/UltiSnips
If UtliSnips snippet have option 'w' in snippet definition you'll get what you want.

**Comment by lpil** [comment]
Closing this as solved.

**Comment by IonicaBizau** [comment]
Thanks, @app and @lpil!
