### ISSUE TITLE
Snippet name collision in CPP and C snippets

### ISSUE THREAD

**Issue by dnivra** [honza/vim-snippets#695]
Both CPP and C snippet files contain a snippet named 'inc'. Since CPP extends C but doesn't seem to override the 'inc' snippet from C, we've to choose which snippet we would like to insert everytime. Is it possible to specify some sort of priority so that CPP snippet is insert by default in CPP files?

**Comment by lpil** [comment]
I don't know of a way to do this off the top of my head, but we could rename one if that makes sense.

**Comment by dnivra** [comment]
[UltiSnips/cpp.snippets](https://github.com/honza/vim-snippets/blob/master/UltiSnips/cpp.snippets#L6) has a priority setting. Could that be used?

**Comment by wanchaol** [comment]
I also found this issue, but no way to fix it. Could anyone tell me how to avoid this?

**Comment by lpil** [comment]
We could always rename one

**Comment by dnivra** [comment]
@lpil If there's no other alternative than renaming the snippet, sure that sounds fine to me.

**Comment by lpil** [comment]
Go for it :)
