### ISSUE TITLE
the javascript's `ret` breaks a line

### ISSUE THREAD

**Issue by itsNikolay** [honza/vim-snippets#707]
when you are typing:
`ret<tab>`
it's replaced by (with line break):
```
return ;

```
( https://github.com/honza/vim-snippets/blob/master/snippets/javascript/javascript.snippets#L96-L98 )

Should we remove the line break as it is in `c.snippets` ?
( https://github.com/honza/vim-snippets/blob/master/snippets/c.snippets#L101-L102 )

**Comment by lpil** [comment]
Sounds good. Make a PR :)
