### ISSUE TITLE
C++ snippets not being expanded in parenthesis, angle brackets etc.

### ISSUE THREAD

**Issue by pmalek** [honza/vim-snippets#708]
This is a copy of https://github.com/SirVer/ultisnips/issues/675 since it was pointed out by @seletskiy that is belongs here rather then in ultisnips.

---

Having C++ snippets like [these ones from honza/vim-snippets](https://github.com/honza/vim-snippets/blob/master/snippets/cpp.snippets) some of those snippets e.g.

```
## Lambdas
# lamda (one line)
snippet ld
    [${1}](${2}){${3}}
```

will not expand when e.g. in parenthesis. This is especially useful when we write something like:

```
vector.push_back( /* lambda expression should go here */ );
```

or when someone defines snippet like so:

```
# templates
snippet tpn
    typename ${1:T}
```

then it wouldn't expand in:

```
template<tpn /* wouldn't expand here */
```

**Comment by lpil** [comment]
If you want to add the flags to trigger the desired snippets in-word that pull request would be very much welcome :)

http://www.sirver.net/blog/2012/01/08/second-episode-of-ultisnips-screencast/

**Comment by agauniyal** [comment]
Why are cpp snippets included in ultisnips directory in first place? Just remove them, they're incomplete, nor updated and just get in way of snippets/cpp.snippets - which are better imho.

**Comment by lpil** [comment]
No good reason. It would be good to unify the snippets under the snipmate format.

**Comment by lpil** [comment]
Closing as solved.
