### ISSUE TITLE
Rust snippets from other editors

### ISSUE THREAD

**Issue by RustSnippets** [honza/vim-snippets#718]
https://github.com/zargony/atom-language-rust/blob/master/snippets/rust.cson
https://github.com/abaez/ta-rust/blob/master/snippets.lua
https://github.com/freebroccolo/rust-snippets/blob/master/rust-snippets.el
https://github.com/rust-lang/sublime-rust/tree/master/snippets

Maybe you can add the missing snippets from other editors and implement it in your project.

**Comment by lpil** [comment]
Sounds like a good idea. Fancy taking a shot at this yourself and adding them to the `snippets`directory?
