### ISSUE TITLE
PHPSpec snippets - PR or own Ultisnips repo? 

### ISSUE THREAD

**Issue by codeinabox** [honza/vim-snippets#724]
If I wanted to add PHPSpec snippets is it better if I raise a PR or create my own Ultisnips repo?

**Comment by lpil** [comment]
We're happy to accept new snippets here :)

**Comment by codeinabox** [comment]
Have created PR #725

**Comment by codeinabox** [comment]
@lpil a question I have is what is the convention for naming snippet and is it good practice to assign lots of different options to one? eg multiple values for `assert` https://github.com/noahfrederick/dots/blob/master/vim/snips/php_phpunit.snippets

**Comment by lpil** [comment]
It's best not to have multiple snippets with the same name. Instead consider adding a trailing letter or something to differentiate each one.
