### ISSUE TITLE
Integration tests for snippets 

### ISSUE THREAD

**Issue by codeinabox** [honza/vim-snippets#730]
Have you considered adding integration tests for snippets? If this is of interest I could create a PR, vader makes this quite easy eg https://github.com/voronkovich/ctrlp-symfony2.vim/pull/5

**Comment by lpil** [comment]
I'm interested in making one. Would need a way of determining each snippet for each language.

I think the Ruby vim library that the Elixir vim project uses might be a better fit than Vader.

**Comment by codeinabox** [comment]
Wouldn't Vader allow you to test snippets via Ultisnips, executing Vimscript to check the snippets work as expected?

**Comment by lpil** [comment]
Yes, but you need a way of metaprogramming the test cases for each snippet, which sounds much harder in Vader.
