### ISSUE TITLE
`vaf` only expands on `af`

### ISSUE THREAD

**Issue by adam-beck** [honza/vim-snippets#732]
When typing `vaf` and expanding the snippet my result is:

```js
vfunction() {

}
```

but expect

```js
var function_name = function() {

}
```

Everything besides the "v" belongs to the snippet `af` so I think they are somehow getting combined. I could very well have something configured wrong. Other combinations (`if` & `ife`) do not have this problem. If I rename the snippet to something like `vaff` it works as well (and removes the `vaf` so I know it isn't defined elsewhere). It's oddly enough only the `vaf` trigger. Any ideas?

**Comment by honza** [comment]
What language is this for?

**Comment by adam-beck** [comment]
Javascript.

**Comment by adam-beck** [comment]
I was looking at the wrong snippets. I apologize. I'm using UltiSnips and was looking at the syntax for SnipMate.

**Comment by adam-beck** [comment]
@honza if you think this is a problem that UltiSnips can't properly use the snippets designed for SnipMate then we can repopen. I don't know why that one is the only one causing problems (from what I've explored so far). I'm new to using snippets and the different plugins surrounding them.

**Comment by honza** [comment]
:+1:
