### ISSUE TITLE
PHP 7 strict type snippets

### ISSUE THREAD

**Issue by codeinabox** [honza/vim-snippets#741]
PHP 7 was released recently and it introduces strict typing which could be added to say the getter snippets, example below. If I wanted to make strictly typed snippets optional what's the best way? A set of snippets you can enable that override the existing ones?

Existing
```php
/**
 * Getter for name
 *
 * @return string
 */
public function getName()
{
    return $this->name;
}
```

Strict type
```php
/**
 * Getter for name
 *
 * @return string
 */
public function getName() : string
{
    return $this->name;
}
```

**Comment by codeinabox** [comment]
@chrisyue @lpil any thoughts?

**Comment by lpil** [comment]
I'm unsure I'm afraid

**Comment by codeinabox** [comment]
I think I've come up with an idea. Ultisnips has a feature called context snippets that I could use to detect if the file contains "declare(strict_types=1)" and hence the strict snippet should be used. I will give this a try and if it works well raise a PR.

**Comment by lpil** [comment]
Cool, looking forward to seeing what you come up with

**Comment by codeinabox** [comment]
I've asked to find out if this is possible https://github.com/SirVer/ultisnips/issues/712

**Comment by codeinabox** [comment]
I've got it working using context aware snippets but I wonder if it creates too much duplication

```viml
global !p
import vim

def isPHPStrictTypes(snip):
	return re.match('<\?php\s+declare\(strict_types=1\);', '\n'.join(snip.buffer))
endglobal

snippet gm "Strict Type PHP Class Getter" "isPHPStrictTypes(snip)" be
/**
 * Getter for $1
 *
 * @return ${2:string}
 */
public function get${1/\w+\s*/\u$0/}(): $2
{
    return $this->$1;
}
endsnippet
```

Would adding a conditional inside the snippets be a better approach? Something like this though getting errors

```viml
snippet gm "PHP Class Getter" b
/**
 * Getter for $1
 *
 * @return ${2:string}
 */
public function get${1/\w+\s*/\u$0/}()`!p snip.rv = ': '+t[2] if isPHPStrictTypes(snip) else ''`
{
    return $this->$1;
}
endsnippet
```
