### ISSUE TITLE
Need Sass snippet

### ISSUE THREAD

**Issue by wildskyf** [honza/vim-snippets#747]
FYI: http://sass-lang.com/documentation/file.SASS_REFERENCE.html

**Comment by lpil** [comment]
Pull requests welcome

**Comment by honza** [comment]
Yes, this would be a nice set of snippets.

**Comment by wildskyf** [comment]
@honza you could read the commit in #748 and give me some other suggestion (If any) so that I could add them into `sass.snippets` :)

**Comment by wildskyf** [comment]
close via #748
