### ISSUE TITLE
UltiSnipsAddFiletypes not working with autocmd

### ISSUE THREAD

**Issue by zirho** [honza/vim-snippets#749]
Hi, 

I freshly installed vim (tried MacVim too)
and installed Vundle, Ultisnips, and vim-snippets.

and when I open a javascript file
running command below makes jasmine snippets available.

```
:UltiSnipsAddFiletypes javascript-jasmine
```

but in .vimrc 

```
autocmd FileType javascript UltiSnipsAddFiletypes javascript-jasmine
```

does not work.

I made sure the "UltiSnipsAddFiletypes" command is called when I open javascript file.

How can I troubleshoot it further?

**Comment by codeinabox** [comment]
If you open a JavaScript file and type `echo &filetype` does it say javascript or something else?

**Comment by zirho** [comment]
the file type was jasmine.javascript 
so it runs jasmine type first and javascript accordingly.
I put some other commands to test if the commands is run and verified it was being called.

Maybe I should just use .vim/ftplugin/javascript.vim to load jasmine snippets.
I'll try it.

thanks

**Comment by codeinabox** [comment]
Have you tried `autocmd FileType jasmine.javascript UltiSnipsAddFiletypes javascript-jasmine`

**Comment by zirho** [comment]
Yes I tried 
```
autocmd FileType javascript UltiSnipsAddFiletypes javascript-jasmine
autocmd FileType jasmine UltiSnipsAddFiletypes javascript-jasmine
autocmd FileType jasmine.javascript UltiSnipsAddFiletypes javascript-jasmine
autocmd FileType js UltiSnipsAddFiletypes javascript-jasmine
```

**Comment by zirho** [comment]
Even when I enabled jasmine snippets with ```:UltiSnipsAddFiletypes javascript-jasmine``` this command.
moving to other split views and coming back makes it goes away.

Can this be some sort of hint?

thanks

**Comment by lpil** [comment]
Seems like a good one to take up with the snippet engine as it is what provides this feature :)
