### ISSUE TITLE
Self-closing HTML tags

### ISSUE THREAD

**Issue by indiesquidge** [honza/vim-snippets#752]
Any reason why some HTML snippets are not using self-closing tags for elements, like `input`, `hr`, and `br`, but other elements are using self-closing tags, like `img`?

I'm not sure whether having them is standard with the W3C spec or not at this point, but it seems like things may sometimes still break without them (e.g., `JSX`). Would it be safer to just include them for [void elements](http://w3c.github.io/html/syntax.html#void-elements) in this library? If so, I'd be happy to create a PR to update the snippets.

**Comment by lpil** [comment]
I don't think there's any real reason here. Happy to accept PRs :)
