### ISSUE TITLE
sh snippets !env and #! not working

### ISSUE THREAD

**Issue by tommyc38** [honza/vim-snippets#789]
# ! doesn't work at all.  It doesn't populate list of options

!env populates but only after typing three characters.  When I navigate to it in the drop down menu it changes my input to !!env.  Also, modeline also comes up as an option with "!en" which is odd. Lastly, it doesn't expand.  I have tested other snippets and they work fine.  

Thanks!

**Comment by tommyc38** [comment]
!env works if you type "ev".

**Comment by lpil** [comment]
This seems like an issue for your snippet's engine's repo.
