### ISSUE TITLE
How UltiSnips add javascript.es6.react.snippets

### ISSUE THREAD

**Issue by zewait** [honza/vim-snippets#823]
I add it like this
```
vi ~/.vim/after/ftplugin/javascript.vim

UltiSnipsAddFiletypes javascript.es6.react
```
don't work, UltiSnips's introductions
> :UltiSnipsAddFiletypes ruby.programming
> The priority will then be rails -> ruby -> programming -> all.

something I mistake?

**Comment by lpil** [comment]
Seems like a question for your snippet engine's repo.
