### ISSUE TITLE
polymer support

### ISSUE THREAD

**Issue by mess110** [honza/vim-snippets#825]
Hello

I would like to add polymer snippets support.

I converted https://github.com/robdodson/PolymerSnippets to a file called _html-polymer.snippets_ and I am not sure I know the correct naming conventions :) . Polymer file type is html.

In the snippets folder, I have a folder html where I have my html snippets and my polymer snippets (2 different files). If I would submit a pull request (and assuming there is interest for this) I imagine I would also have to create a folder html and move [html.snippets](https://github.com/honza/vim-snippets/blob/master/snippets/html.snippets) in there. Would I also have to move [htmldjango.snippets](https://github.com/honza/vim-snippets/blob/master/snippets/htmldjango.snippets) and [htmltornado.snippets](https://github.com/honza/vim-snippets/blob/master/snippets/htmltornado.snippets)?

Thank you

**Comment by lpil** [comment]
Best to leave it as `html-polymer.snippets` and let people manually add them rather than having them included by default :)
