### ISSUE TITLE
Type Hinting in PHP constructor snippet

### ISSUE THREAD

**Issue by Eluminae** [honza/vim-snippets#830]
Hello everyone,
I just discovered UltiSnips and this vim snippets and I really want to thank you for your amazing work.

I only have one little problem : 
When I try to use snippet to create a php constructor, the Type Hint make my vars attribution bug.

I have something like this :
    /** 
     * @param mixed Email $varA
     */
    public function __construct(Email $varA)
    {Email·
        $this->varA = $varA;
    }

Does anyone got a solution ? Am I doing something wrong ? How can this issue be solved ?

Thank you a lot for your attention. <3

**Comment by WouterSioen** [comment]
@Eluminae @nbicalcarata I made a fix for this: https://github.com/honza/vim-snippets/pull/1049 Can you guys test if it works as you expect it?

**Comment by Eluminae** [comment]
It's very cool dude TY !

I found something, when you tri to typehint "\DateTime", the rendered is 
```php
/**
 * Setter for createdAt
 *
 * @param \DateTime $createdAt
 * @return self
 */
public function setCreatedAt(DateTime $createdAt)
{
    $this->createdAt = $createdAt;

    return $this;
}
```

The "\\" disappeared in the argument list !

In fact, every "\\" disappear. Try to use a full FQCN and the result is a little sad.

This problem probably exist outside the setter context. Maybe am I doing something badly ?

Ty again !

**Comment by WouterSioen** [comment]
Hmm, well spotted, will look into it.

**Comment by WouterSioen** [comment]
I actually didn't change anything about the setter snippet, so this isn't introduced by my change.

**Comment by Eluminae** [comment]
Yeah I thing the "\\" char is ignored when word is propagate.

**Comment by WouterSioen** [comment]
I looked into it but couldn't really find a way to fix it at the moment. Since I don't use that snippet myself, it's not really bothering me too, so I won't spend too much time on it at the moment.

I hope somebody finds a solution though to get this inconsistency fixed.
