### ISSUE TITLE
Use clipboard content in snippets

### ISSUE THREAD

**Issue by nerdpad** [honza/vim-snippets#832]
Is it possible to use the clipboard content in a snippet? Something like this:

Suppose I yank a word and invoke the javascript ```fun``` snippet. Instead of the first substitution read ```function_name``` can it read the value that's in the clipboard?

```
snippet fun
	function ${1:<yanked word>}(${2}) {
		${0}
	}
```

Thanks.

**Comment by honza** [comment]
I think you'd be more likely to get an answer on the engine's project page. Off the top of my head, I don't remember this being possible. Others can correct me.

**Comment by codeinabox** [comment]
If the snippet uses VISUAL you can just do this http://vimcasts.org/episodes/ultisnips-visual-placeholder/

**Comment by cirosantilli** [comment]
You can achieve this with backticks + `@+`, e.g.:

    asdf
        qwer`@+`zxcv

You can also set defaults to clipboard alternatively: https://github.com/honza/vim-snippets/blob/a11cf5b47fcb9de72b5c8694a4e2fe2dca8c0ae7/snippets/markdown.snippets#L11
