### ISSUE TITLE
Wrong output for .tex file with plugin snipmate

### ISSUE THREAD

**Issue by lrtfm** [honza/vim-snippets#833]
When I insert  `it<TAB>`, I just get a `textit{text}` with out the backslash. It should be `\textit{text}`.
Does we need update the `tex.snippets` file because  snipmate need `\\` to produce a  single backslash?

My `.vimrc` file includes the following lines:
```
let g:snipMate = {}
let g:snipMate.snippet_version = 1
```
Without these two lines, the output is `\textit{${VISUAL:text}}`. It is also a mistake.

How can I fixed these errors?

**Comment by lpil** [comment]
Is this fixed now?

**Comment by lrtfm** [comment]
@lpil [#835](https://github.com/honza/vim-snippets/pull/835) will fixed this.

**Comment by lpil** [comment]
Thank you
