### ISSUE TITLE
Error using tex snippet with ultisnips using neovim

### ISSUE THREAD

**Issue by frdrcv** [honza/vim-snippets#838]
With vim, vim-snippets with UltiSnips is working flawlessly, but since I migrated to neovim, I get a weird error when trying to use a tex snippet :

> An error occured. This is either a bug in UltiSnips or a bug in a
> snippet definition. If you think this is a bug, please report it to
> https://github.com/SirVer/ultisnips/issues/new.
> 
> Following is the full stack trace:
> Traceback (most recent call last):
>   File "/home/nrfrd/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
>     return func(self, *args, **kwds)
>   File "/home/nrfrd/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 124, in expand
>     if not self._try_expand():
>   File "/home/nrfrd/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 702, in _try_expand
>     snippets = self._snips(before, False, autotrigger_only)
>   File "/home/nrfrd/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 575, in _snips
>     source.ensure(filetypes, cached=autotrigger_only)
>   File "/home/nrfrd/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 47, in ensure
>     self._load_snippets_for(ft)
>   File "/home/nrfrd/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 80, in _load_snippets_for
>     self._parse_snippets(ft, fn)
>   File "/home/nrfrd/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 99, in _parse_snippets
>     raise SnippetSyntaxError(filename, line_index, msg)
> UltiSnips.snippet.source.file._base.SnippetSyntaxError: Invalid line 'version 1' in 
>  ~/.local/share/nvim/plugged/vim-snippets/snippets/tex.snippets:1

I thought that it could be a problem with Ultisnips being incompatible with neovim, but I took a look at the first line of tex.snippets file as indicated by the last line in this error and if I comment it out, the problem stops. Shouldn't this line be commented out by default (what's the use of `version 1`)? Or could the problem be something else?

**Comment by lpil** [comment]
Those snippets have just changed. I think that maybe we introduced a bug.

**Comment by frdrcv** [comment]
A coincidence then; thanks for the quick answer.
