### ISSUE TITLE
Is defined1 a typo?

### ISSUE THREAD

**Issue by phunehehe** [honza/vim-snippets#844]
I saw a bunch of "TODO: to be defined1" in some code and was curious to search for it. One thing after another, I ended up here https://github.com/honza/vim-snippets/blob/fcbccd48d526241d902c29143ea66c95e58c2447/UltiSnips/python.snippets#L263.
Is this a typo, or does it mean something special?

**Comment by lpil** [comment]
I've no idea. :)

**Comment by lpil** [comment]
Seems like a mistake -> https://github.com/honza/vim-snippets/commit/59dcc2b72d9dc070d13bb711406fed6e666366d6#diff-26492e464212ddf5632232982a008b60R126

Wanna fix it? :)
