### ISSUE TITLE
Sass abbreviations expand with ";"

### ISSUE THREAD

**Issue by iurevych** [honza/vim-snippets#846]
I'm a front-end developer using Sass. When expanding Sass abbreviations they expand just like CSS ones, having ";" after each property. Sass != SCSS as their syntax is different. It is wrong to assume that inside `sass.snippets` you can do `extends css` and add few Sass specific things to it.

Is there an easy fix for it? I'm about to paste all CSS snippets without `;` character into `sass.snippets` manually.

Just wondering if this is just me or everyone else that sees this issue.

In case you need my `.vimrc`: https://gist.github.com/iurevych/927d6c90acd6b05b87378f806ba02402

Here is a screenshot on what's happening as soon as I press `Tab`:
![layouts - vim 2017-01-10 00-22-10](https://cloud.githubusercontent.com/assets/325422/21786071/eb0940c8-d6ca-11e6-85f7-4c72c2f1d6fb.png)

`set ft?` shows "sass", no issues with filetype.

MacVim: 8.0 (120)
Mac OS Sierra 10.12.1

Thanks!

**Comment by lpil** [comment]
I believe the right solution is to remove the extend and then copy and modify the snippets.
