### ISSUE TITLE
Moving React snippets into jsx.snippets?

### ISSUE THREAD

**Issue by codeinabox** [honza/vim-snippets#851]
Would it make sense to move the React snippets into jsx.snippets?

**Comment by lpil** [comment]
If they are currently in the default JS namespace we should probably move them out into a library namespace.

**Comment by codeinabox** [comment]
They are already in a library namespace but should they be further moved out into a syntax namespace? Though I guess you can have React without JSX

**Comment by lpil** [comment]
I think it's fine as it is then. JSX isn't really a language, just
syntactic sugar overload.
