### ISSUE TITLE
Please use the same snippet keyword for snippets doing the same in `UltiSnips` and `snippets

### ISSUE THREAD

**Issue by kiryph** [honza/vim-snippets#856]
I use the plugin neocomplete, UltiSnips and this repository for a base set of snippets.

In a tex document, there is an ultisnips snippet and a snipmate snippet for the itemize environment.

However, they use different trigger words (item and itemize), so the popup menu is more polluted than I want.

![itemize-snippet-vim](https://cloud.githubusercontent.com/assets/371756/22240913/67a93a54-e21d-11e6-827c-5601b2a33ac7.png)

With following trigger words, I see only one snippet for the itemize env anymore, since UltiSnips considers only the snippet on the snippet search path with the highest priority (see https://github.com/SirVer/ultisnips/commit/4b4ee488580f7586e82a76bb392e4f79027ce049)

```diff
diff --git a/snippets/tex.snippets b/snippets/tex.snippets
index 0b9caf8..c095b5a 100644
--- a/snippets/tex.snippets
+++ b/snippets/tex.snippets
@@ -86,11 +86,11 @@ snippet enumi enumerate environment
                \\item ${0}
        \\end{enumerate}
 # Itemize
-snippet itemize itemize environment
+snippet item itemize environment
        \\begin{itemize}
                \\item ${0}
        \\end{itemize}
-snippet item \item
+snippet it \item
        \\item ${1:${VISUAL}}
 # Description
 snippet desc description environment
```

A related discussion is https://github.com/SirVer/ultisnips/issues/233. The author of ultisnips does not allow to remove the folder `snippets` from the snippets search path, which I would do and add all snippets I use to the Ultisnips snippets file.

**Comment by lpil** [comment]
PRs to resolve this would be very welcome :)
