### ISSUE TITLE
Can I change the "snippet_dirs" to a seperate Dropbox folder?

### ISSUE THREAD

**Issue by llinfeng** [honza/vim-snippets#887]
## Feature request

I use snippets on a hourly basis, and more often than not, I will make changes to the snippets. However, currently, all snippets seems to be canned within the Vim-snipmate plugin. Thus, it makes it very hard to me to keep the snippets up-to-date when I switch workstations (e.g., from a Windows desktop machine to a laptop).

It would nice to give users an option to **source** a specific folder outside the installation package of the plugin.

## Failed attempts
1. Tried to change the following setting, in vain:
```    vim
let g:SnipMate['snippet_dirs']
                \ = funcref#Function('return split(&runtimepath,",")')
```
2. Tried to add the following to my `_vimrc` (on a Windows machine):
``` vim
    set rtp+=c:\Users\llinfeng\Dropbox\snippet\
```

**Comment by codeinabox** [comment]
This is a question for your snippet engine.

**Comment by lpil** [comment]
Yup, best ask at those projects :)

**Comment by llinfeng** [comment]
Opps, my bad. Mistook this repo as my snippet engine :)
