### ISSUE TITLE
Syntax for specifying "alias" for snippets?

### ISSUE THREAD

**Issue by llinfeng** [honza/vim-snippets#896]
As I tend to forget the snippets that I defined by myself, I tend to make multiple copies of the same structure and give them a bunch of names. Simply in hope of hitting one of snippets when I need the structure. However, this duplication of snippets does not look clean.

Can I build, say, "alias" structure to my file-type specific `*.snippets` script? So far, I only found an implementation of an aliases dictionary for file-types/scopes.

Thanks a lot!

**Comment by lpil** [comment]
Probably a good one to ask over at your snippet engine's repo. I'd be interested in hearing the answer, report back if you find out :)
