### ISSUE TITLE
Some clarification about ./UltiSnips vs ./snippets

### ISSUE THREAD

**Issue by paranormal** [honza/vim-snippets#910]
> - Currently all snippets from UltiSnips have been put into UltiSnips - some work on merging should be done (dropping duplicates etc). Also see engines section above.

This part is unclear for me.

Merging to what destination? Is preferred format Ultisnip or snipmate?

**Comment by lpil** [comment]
The snipmate format is the preferred format as it can be read by most engines.

If you'd like to clarify that section please send a PR :)

**Comment by polyzen** [comment]
Referencing #363.
