### ISSUE TITLE
Conflicts between snippets and python modules

### ISSUE THREAD

**Issue by guivc** [honza/vim-snippets#913]
The snippet `time` ([all.snippets](https://github.com/honza/vim-snippets/blob/master/UltiSnips/all.snippets#L91)) has conflicts with the module time when using the snippet `from` ([python.snippets](https://github.com/honza/vim-snippets/blob/master/UltiSnips/python.snippets#L529)). 

**How to reproduce the problem?**

If I write:

`from<tab> time<tab> import Stuff`

Wont work because the time get replaced by the current time on local machine and the snippet leaves me with something like `from 15:00 import Stuff`.

How to solve it?

**Comment by lpil** [comment]
Press `<Right>` before hitting tab perhaps? :)

**Comment by gu10ng1t** [comment]
Hey @lpil, thanks for the suggestion. 

Well... At the moment I don't have any mappings for <Right> in insert mode... I think that it's a good time to choose a good one!

If anyone else has any other suggestion let me known!

**Comment by lpil** [comment]
Another one is to have a different key for triggering a snippet as to move to the next field. This is what Ultisnips does by default.
