### ISSUE TITLE
Nested tab stop doesn't work.

### ISSUE THREAD

**Issue by balalaXD** [honza/vim-snippets#918]
Here is snippet div copyed from doc/SnipMate.txt
![config](https://cloud.githubusercontent.com/assets/16096559/26389174/21990dd8-408b-11e7-848b-616983a336dd.png)

And give it a try:
![run](https://cloud.githubusercontent.com/assets/16096559/26389179/246c5470-408b-11e7-88b9-fae21696da8e.png)

It doesn't work as expect, so did i forget to do something important? 

Thanks for your help :)

**Comment by balalaXD** [comment]
It works now, i don't know what's happen.
so pls closed this issue.

**Comment by balalaXD** [comment]
Any finally why doesnt take snipMate.snippet_version=1 as default? Isn't version 0 already legacy, right?

**Comment by balalaXD** [comment]
Put these two lines below to your .vimrc file
let g:snipMate = {}
let g:snipMate.snippet_version = 1

**Comment by lpil** [comment]
This is probably an issue open with your snippet engine as it provides this feature. :)
