### ISSUE TITLE
Looks like you missing end parenthesis at line 19 in haml.snippets

### ISSUE THREAD

**Issue by yyandrew** [honza/vim-snippets#938]
it should be `= render :partial => "${1:item}", :locals => { :${2:$1} => ${0:@$1} }` instead of `= render :partial => "${1:item}", :locals => { :${2:$1} => ${0:@$1}`

**Comment by lpil** [comment]
Could you fix this please? :)

**Comment by yyandrew** [comment]
My pleasure :)

**Comment by lpil** [comment]
Thanks!
