### ISSUE TITLE
Snippet name collision in tex.snippets between \item and \textit

### ISSUE THREAD

**Issue by dnivra** [honza/vim-snippets#940]
The it snippet is assigned for both \item and \textit. Sometimes, the autocomplete chooses \item(even if not within an itemize environment) but occasionally asks which to choose(for instance, when inserting the snippet inside a \item of an itemize environment).

**Comment by dnivra** [comment]
I suppose the issue was probably introduced in ccd2a4f.

**Comment by lpil** [comment]
Would you like to revert this change? :)

**Comment by dnivra** [comment]
I'm not sure if revert is sufficient: the original reason for the commit was probably to synchronize the snippet names(#856). I think a rename of the 'item' to 'itemize' in UltiSnips/tex.snippets would be required too. Personally, I feel name 'item' to insert an 'itemize' is bad because \item is also a valid TeX command and thus, leads to some confusion. However, I think more inputs would be useful.

**Comment by dnivra** [comment]
I created a new pull request(#947) to resolve this. I felt it's better to rename the \textit snippet to resolve the collision.
