### ISSUE TITLE
rust 'allow' snippet default text

### ISSUE THREAD

**Issue by HongxuChen** [honza/vim-snippets#944]
The placeholder default texts for `allow` in rust should be 'unused_variables', rather than 'unused_variable'. See the patch for detail.
[0001-correct-allow-snippet-default.patch.zip](https://github.com/honza/vim-snippets/files/1102592/0001-correct-allow-snippet-default.patch.zip)

**Comment by lpil** [comment]
Would you like to make a pull request resolving this? :)

**Comment by HongxuChen** [comment]
@lpil It's a tiny patch. I guess no need for a PR 😄
