### ISSUE TITLE
`ed` defined for both a jasmine and es6 snippet

### ISSUE THREAD

**Issue by ricbermo** [honza/vim-snippets#946]
triggering `ed` triggers both `export default` from es6 and `expect().toBeDefined()` from jasmine.
 I'm not sure if this is intended or an actual issue.

**Comment by lpil** [comment]
Could you change the jasmine one to use a longer trigger please? :)

**Comment by ricbermo** [comment]
sure, sorry for the late response.

**Comment by ricbermo** [comment]
https://github.com/honza/vim-snippets/pull/951

**Comment by lpil** [comment]
Thanks for the fix! :)
