### ISSUE TITLE
Snippet files with a dash don't load

### ISSUE THREAD

**Issue by cjbassi** [honza/vim-snippets#993]
There's a bunch of files in the `UltiSnips` folder that don't load because UltiSnips expects an underscore instead of a dash after the filetype in the base filename. e.g. `javascript_node.snippets` instead of `javascript-node.snippets`. Either renaming them or putting them into a folder for the specific filetype should fix it. Are there any reasons against doing this? If there's some snippet conflicts it shouldn't be hard to fix those. There's also a few files in the `snippets` folder too that have the same issue.

**Comment by lpil** [comment]
These files are deliberately not loaded by default as they are for specific libraries. If you wish to use them please manually add them in your vim config

**Comment by QzCurious** [comment]
@lpil can you give me some example how to manally add snippets? I didn't find there is a way in *UltiSnips-how-snippets-are-loaded*.
Also, if a snippet can be load while I'm in vim, I'd like to know.

If it's that I lack of some knowlagde, please give me some direction to learn so.
Thanks.
